/* ccnetobj.c generated by valac 0.34.4, the Vala compiler
 * generated from ccnetobj.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define CCNET_TYPE_PROC (ccnet_proc_get_type ())
#define CCNET_PROC(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_PROC, CcnetProc))
#define CCNET_PROC_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_PROC, CcnetProcClass))
#define CCNET_IS_PROC(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_PROC))
#define CCNET_IS_PROC_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_PROC))
#define CCNET_PROC_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_PROC, CcnetProcClass))

typedef struct _CcnetProc CcnetProc;
typedef struct _CcnetProcClass CcnetProcClass;
typedef struct _CcnetProcPrivate CcnetProcPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define CCNET_TYPE_EMAIL_USER (ccnet_email_user_get_type ())
#define CCNET_EMAIL_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_EMAIL_USER, CcnetEmailUser))
#define CCNET_EMAIL_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_EMAIL_USER, CcnetEmailUserClass))
#define CCNET_IS_EMAIL_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_EMAIL_USER))
#define CCNET_IS_EMAIL_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_EMAIL_USER))
#define CCNET_EMAIL_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_EMAIL_USER, CcnetEmailUserClass))

typedef struct _CcnetEmailUser CcnetEmailUser;
typedef struct _CcnetEmailUserClass CcnetEmailUserClass;
typedef struct _CcnetEmailUserPrivate CcnetEmailUserPrivate;

#define CCNET_TYPE_GROUP (ccnet_group_get_type ())
#define CCNET_GROUP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_GROUP, CcnetGroup))
#define CCNET_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_GROUP, CcnetGroupClass))
#define CCNET_IS_GROUP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_GROUP))
#define CCNET_IS_GROUP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_GROUP))
#define CCNET_GROUP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_GROUP, CcnetGroupClass))

typedef struct _CcnetGroup CcnetGroup;
typedef struct _CcnetGroupClass CcnetGroupClass;
typedef struct _CcnetGroupPrivate CcnetGroupPrivate;

#define CCNET_TYPE_GROUP_USER (ccnet_group_user_get_type ())
#define CCNET_GROUP_USER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_GROUP_USER, CcnetGroupUser))
#define CCNET_GROUP_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_GROUP_USER, CcnetGroupUserClass))
#define CCNET_IS_GROUP_USER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_GROUP_USER))
#define CCNET_IS_GROUP_USER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_GROUP_USER))
#define CCNET_GROUP_USER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_GROUP_USER, CcnetGroupUserClass))

typedef struct _CcnetGroupUser CcnetGroupUser;
typedef struct _CcnetGroupUserClass CcnetGroupUserClass;
typedef struct _CcnetGroupUserPrivate CcnetGroupUserPrivate;

#define CCNET_TYPE_ORGANIZATION (ccnet_organization_get_type ())
#define CCNET_ORGANIZATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_ORGANIZATION, CcnetOrganization))
#define CCNET_ORGANIZATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_ORGANIZATION, CcnetOrganizationClass))
#define CCNET_IS_ORGANIZATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_ORGANIZATION))
#define CCNET_IS_ORGANIZATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_ORGANIZATION))
#define CCNET_ORGANIZATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_ORGANIZATION, CcnetOrganizationClass))

typedef struct _CcnetOrganization CcnetOrganization;
typedef struct _CcnetOrganizationClass CcnetOrganizationClass;
typedef struct _CcnetOrganizationPrivate CcnetOrganizationPrivate;

#define CCNET_TYPE_PEER_STAT (ccnet_peer_stat_get_type ())
#define CCNET_PEER_STAT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CCNET_TYPE_PEER_STAT, CcnetPeerStat))
#define CCNET_PEER_STAT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CCNET_TYPE_PEER_STAT, CcnetPeerStatClass))
#define CCNET_IS_PEER_STAT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CCNET_TYPE_PEER_STAT))
#define CCNET_IS_PEER_STAT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CCNET_TYPE_PEER_STAT))
#define CCNET_PEER_STAT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CCNET_TYPE_PEER_STAT, CcnetPeerStatClass))

typedef struct _CcnetPeerStat CcnetPeerStat;
typedef struct _CcnetPeerStatClass CcnetPeerStatClass;
typedef struct _CcnetPeerStatPrivate CcnetPeerStatPrivate;

struct _CcnetProc {
	GObject parent_instance;
	CcnetProcPrivate * priv;
	gchar* _name;
	gint _ctime;
	gint _dtime;
};

struct _CcnetProcClass {
	GObjectClass parent_class;
};

struct _CcnetProcPrivate {
	gchar* _peer_name;
};

struct _CcnetEmailUser {
	GObject parent_instance;
	CcnetEmailUserPrivate * priv;
};

struct _CcnetEmailUserClass {
	GObjectClass parent_class;
};

struct _CcnetEmailUserPrivate {
	gint _id;
	gchar* _email;
	gboolean _is_staff;
	gboolean _is_active;
	gint64 _ctime;
	gchar* _source;
	gchar* _role;
	gchar* _password;
};

struct _CcnetGroup {
	GObject parent_instance;
	CcnetGroupPrivate * priv;
};

struct _CcnetGroupClass {
	GObjectClass parent_class;
};

struct _CcnetGroupPrivate {
	gint _id;
	gchar* _group_name;
	gchar* _creator_name;
	gint64 _timestamp;
	gchar* _source;
};

struct _CcnetGroupUser {
	GObject parent_instance;
	CcnetGroupUserPrivate * priv;
};

struct _CcnetGroupUserClass {
	GObjectClass parent_class;
};

struct _CcnetGroupUserPrivate {
	gint _group_id;
	gchar* _user_name;
	gint _is_staff;
};

struct _CcnetOrganization {
	GObject parent_instance;
	CcnetOrganizationPrivate * priv;
};

struct _CcnetOrganizationClass {
	GObjectClass parent_class;
};

struct _CcnetOrganizationPrivate {
	gint _org_id;
	gchar* _email;
	gint _is_staff;
	gchar* _org_name;
	gchar* _url_prefix;
	gchar* _creator;
	gint64 _ctime;
};

struct _CcnetPeerStat {
	GObject parent_instance;
	CcnetPeerStatPrivate * priv;
};

struct _CcnetPeerStatClass {
	GObjectClass parent_class;
};

struct _CcnetPeerStatPrivate {
	gchar* _id;
	gchar* _name;
	gchar* _ip;
	gboolean _encrypt;
	gint64 _last_up;
	gint _proc_num;
};


static gpointer ccnet_proc_parent_class = NULL;
static gpointer ccnet_email_user_parent_class = NULL;
static gpointer ccnet_group_parent_class = NULL;
static gpointer ccnet_group_user_parent_class = NULL;
static gpointer ccnet_organization_parent_class = NULL;
static gpointer ccnet_peer_stat_parent_class = NULL;

GType ccnet_proc_get_type (void) G_GNUC_CONST;
#define CCNET_PROC_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CCNET_TYPE_PROC, CcnetProcPrivate))
enum  {
	CCNET_PROC_DUMMY_PROPERTY,
	CCNET_PROC_PEER_NAME,
	CCNET_PROC_NAME,
	CCNET_PROC_CTIME,
	CCNET_PROC_DTIME
};
CcnetProc* ccnet_proc_new (void);
CcnetProc* ccnet_proc_construct (GType object_type);
const gchar* ccnet_proc_get_peer_name (CcnetProc* self);
void ccnet_proc_set_peer_name (CcnetProc* self, const gchar* value);
const gchar* ccnet_proc_get_name (CcnetProc* self);
void ccnet_proc_set_name (CcnetProc* self, const gchar* value);
gint ccnet_proc_get_ctime (CcnetProc* self);
void ccnet_proc_set_ctime (CcnetProc* self, gint value);
gint ccnet_proc_get_dtime (CcnetProc* self);
void ccnet_proc_set_dtime (CcnetProc* self, gint value);
static void ccnet_proc_finalize (GObject* obj);
static void _vala_ccnet_proc_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_ccnet_proc_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType ccnet_email_user_get_type (void) G_GNUC_CONST;
#define CCNET_EMAIL_USER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CCNET_TYPE_EMAIL_USER, CcnetEmailUserPrivate))
enum  {
	CCNET_EMAIL_USER_DUMMY_PROPERTY,
	CCNET_EMAIL_USER_ID,
	CCNET_EMAIL_USER_EMAIL,
	CCNET_EMAIL_USER_IS_STAFF,
	CCNET_EMAIL_USER_IS_ACTIVE,
	CCNET_EMAIL_USER_CTIME,
	CCNET_EMAIL_USER_SOURCE,
	CCNET_EMAIL_USER_ROLE,
	CCNET_EMAIL_USER_PASSWORD
};
CcnetEmailUser* ccnet_email_user_new (void);
CcnetEmailUser* ccnet_email_user_construct (GType object_type);
gint ccnet_email_user_get_id (CcnetEmailUser* self);
void ccnet_email_user_set_id (CcnetEmailUser* self, gint value);
const gchar* ccnet_email_user_get_email (CcnetEmailUser* self);
void ccnet_email_user_set_email (CcnetEmailUser* self, const gchar* value);
gboolean ccnet_email_user_get_is_staff (CcnetEmailUser* self);
void ccnet_email_user_set_is_staff (CcnetEmailUser* self, gboolean value);
gboolean ccnet_email_user_get_is_active (CcnetEmailUser* self);
void ccnet_email_user_set_is_active (CcnetEmailUser* self, gboolean value);
gint64 ccnet_email_user_get_ctime (CcnetEmailUser* self);
void ccnet_email_user_set_ctime (CcnetEmailUser* self, gint64 value);
const gchar* ccnet_email_user_get_source (CcnetEmailUser* self);
void ccnet_email_user_set_source (CcnetEmailUser* self, const gchar* value);
const gchar* ccnet_email_user_get_role (CcnetEmailUser* self);
void ccnet_email_user_set_role (CcnetEmailUser* self, const gchar* value);
const gchar* ccnet_email_user_get_password (CcnetEmailUser* self);
void ccnet_email_user_set_password (CcnetEmailUser* self, const gchar* value);
static void ccnet_email_user_finalize (GObject* obj);
static void _vala_ccnet_email_user_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_ccnet_email_user_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType ccnet_group_get_type (void) G_GNUC_CONST;
#define CCNET_GROUP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CCNET_TYPE_GROUP, CcnetGroupPrivate))
enum  {
	CCNET_GROUP_DUMMY_PROPERTY,
	CCNET_GROUP_ID,
	CCNET_GROUP_GROUP_NAME,
	CCNET_GROUP_CREATOR_NAME,
	CCNET_GROUP_TIMESTAMP,
	CCNET_GROUP_SOURCE
};
CcnetGroup* ccnet_group_new (void);
CcnetGroup* ccnet_group_construct (GType object_type);
gint ccnet_group_get_id (CcnetGroup* self);
void ccnet_group_set_id (CcnetGroup* self, gint value);
const gchar* ccnet_group_get_group_name (CcnetGroup* self);
void ccnet_group_set_group_name (CcnetGroup* self, const gchar* value);
const gchar* ccnet_group_get_creator_name (CcnetGroup* self);
void ccnet_group_set_creator_name (CcnetGroup* self, const gchar* value);
gint64 ccnet_group_get_timestamp (CcnetGroup* self);
void ccnet_group_set_timestamp (CcnetGroup* self, gint64 value);
const gchar* ccnet_group_get_source (CcnetGroup* self);
void ccnet_group_set_source (CcnetGroup* self, const gchar* value);
static void ccnet_group_finalize (GObject* obj);
static void _vala_ccnet_group_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_ccnet_group_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType ccnet_group_user_get_type (void) G_GNUC_CONST;
#define CCNET_GROUP_USER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CCNET_TYPE_GROUP_USER, CcnetGroupUserPrivate))
enum  {
	CCNET_GROUP_USER_DUMMY_PROPERTY,
	CCNET_GROUP_USER_GROUP_ID,
	CCNET_GROUP_USER_USER_NAME,
	CCNET_GROUP_USER_IS_STAFF
};
CcnetGroupUser* ccnet_group_user_new (void);
CcnetGroupUser* ccnet_group_user_construct (GType object_type);
gint ccnet_group_user_get_group_id (CcnetGroupUser* self);
void ccnet_group_user_set_group_id (CcnetGroupUser* self, gint value);
const gchar* ccnet_group_user_get_user_name (CcnetGroupUser* self);
void ccnet_group_user_set_user_name (CcnetGroupUser* self, const gchar* value);
gint ccnet_group_user_get_is_staff (CcnetGroupUser* self);
void ccnet_group_user_set_is_staff (CcnetGroupUser* self, gint value);
static void ccnet_group_user_finalize (GObject* obj);
static void _vala_ccnet_group_user_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_ccnet_group_user_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType ccnet_organization_get_type (void) G_GNUC_CONST;
#define CCNET_ORGANIZATION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CCNET_TYPE_ORGANIZATION, CcnetOrganizationPrivate))
enum  {
	CCNET_ORGANIZATION_DUMMY_PROPERTY,
	CCNET_ORGANIZATION_ORG_ID,
	CCNET_ORGANIZATION_EMAIL,
	CCNET_ORGANIZATION_IS_STAFF,
	CCNET_ORGANIZATION_ORG_NAME,
	CCNET_ORGANIZATION_URL_PREFIX,
	CCNET_ORGANIZATION_CREATOR,
	CCNET_ORGANIZATION_CTIME
};
CcnetOrganization* ccnet_organization_new (void);
CcnetOrganization* ccnet_organization_construct (GType object_type);
gint ccnet_organization_get_org_id (CcnetOrganization* self);
void ccnet_organization_set_org_id (CcnetOrganization* self, gint value);
const gchar* ccnet_organization_get_email (CcnetOrganization* self);
void ccnet_organization_set_email (CcnetOrganization* self, const gchar* value);
gint ccnet_organization_get_is_staff (CcnetOrganization* self);
void ccnet_organization_set_is_staff (CcnetOrganization* self, gint value);
const gchar* ccnet_organization_get_org_name (CcnetOrganization* self);
void ccnet_organization_set_org_name (CcnetOrganization* self, const gchar* value);
const gchar* ccnet_organization_get_url_prefix (CcnetOrganization* self);
void ccnet_organization_set_url_prefix (CcnetOrganization* self, const gchar* value);
const gchar* ccnet_organization_get_creator (CcnetOrganization* self);
void ccnet_organization_set_creator (CcnetOrganization* self, const gchar* value);
gint64 ccnet_organization_get_ctime (CcnetOrganization* self);
void ccnet_organization_set_ctime (CcnetOrganization* self, gint64 value);
static void ccnet_organization_finalize (GObject* obj);
static void _vala_ccnet_organization_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_ccnet_organization_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType ccnet_peer_stat_get_type (void) G_GNUC_CONST;
#define CCNET_PEER_STAT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CCNET_TYPE_PEER_STAT, CcnetPeerStatPrivate))
enum  {
	CCNET_PEER_STAT_DUMMY_PROPERTY,
	CCNET_PEER_STAT_ID,
	CCNET_PEER_STAT_NAME,
	CCNET_PEER_STAT_IP,
	CCNET_PEER_STAT_ENCRYPT,
	CCNET_PEER_STAT_LAST_UP,
	CCNET_PEER_STAT_PROC_NUM
};
CcnetPeerStat* ccnet_peer_stat_new (void);
CcnetPeerStat* ccnet_peer_stat_construct (GType object_type);
const gchar* ccnet_peer_stat_get_id (CcnetPeerStat* self);
void ccnet_peer_stat_set_id (CcnetPeerStat* self, const gchar* value);
const gchar* ccnet_peer_stat_get_name (CcnetPeerStat* self);
void ccnet_peer_stat_set_name (CcnetPeerStat* self, const gchar* value);
const gchar* ccnet_peer_stat_get_ip (CcnetPeerStat* self);
void ccnet_peer_stat_set_ip (CcnetPeerStat* self, const gchar* value);
gboolean ccnet_peer_stat_get_encrypt (CcnetPeerStat* self);
void ccnet_peer_stat_set_encrypt (CcnetPeerStat* self, gboolean value);
gint64 ccnet_peer_stat_get_last_up (CcnetPeerStat* self);
void ccnet_peer_stat_set_last_up (CcnetPeerStat* self, gint64 value);
gint ccnet_peer_stat_get_proc_num (CcnetPeerStat* self);
void ccnet_peer_stat_set_proc_num (CcnetPeerStat* self, gint value);
static void ccnet_peer_stat_finalize (GObject* obj);
static void _vala_ccnet_peer_stat_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_ccnet_peer_stat_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


CcnetProc* ccnet_proc_construct (GType object_type) {
	CcnetProc * self = NULL;
	self = (CcnetProc*) g_object_new (object_type, NULL);
	return self;
}


CcnetProc* ccnet_proc_new (void) {
	return ccnet_proc_construct (CCNET_TYPE_PROC);
}


const gchar* ccnet_proc_get_peer_name (CcnetProc* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_peer_name;
	result = _tmp0_;
	return result;
}


void ccnet_proc_set_peer_name (CcnetProc* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_peer_name);
	self->priv->_peer_name = _tmp1_;
	g_object_notify ((GObject *) self, "peer-name");
}


const gchar* ccnet_proc_get_name (CcnetProc* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_name;
	result = _tmp0_;
	return result;
}


void ccnet_proc_set_name (CcnetProc* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_name);
	self->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


gint ccnet_proc_get_ctime (CcnetProc* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->_ctime;
	result = _tmp0_;
	return result;
}


void ccnet_proc_set_ctime (CcnetProc* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->_ctime = _tmp0_;
	g_object_notify ((GObject *) self, "ctime");
}


gint ccnet_proc_get_dtime (CcnetProc* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->_dtime;
	result = _tmp0_;
	return result;
}


void ccnet_proc_set_dtime (CcnetProc* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->_dtime = _tmp0_;
	g_object_notify ((GObject *) self, "dtime");
}


static void ccnet_proc_class_init (CcnetProcClass * klass) {
	ccnet_proc_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CcnetProcPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_proc_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_proc_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_proc_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PROC_PEER_NAME, g_param_spec_string ("peer-name", "peer-name", "peer-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PROC_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PROC_CTIME, g_param_spec_int ("ctime", "ctime", "ctime", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PROC_DTIME, g_param_spec_int ("dtime", "dtime", "dtime", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void ccnet_proc_instance_init (CcnetProc * self) {
	self->priv = CCNET_PROC_GET_PRIVATE (self);
}


static void ccnet_proc_finalize (GObject* obj) {
	CcnetProc * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_PROC, CcnetProc);
	_g_free0 (self->priv->_peer_name);
	_g_free0 (self->_name);
	G_OBJECT_CLASS (ccnet_proc_parent_class)->finalize (obj);
}


GType ccnet_proc_get_type (void) {
	static volatile gsize ccnet_proc_type_id__volatile = 0;
	if (g_once_init_enter (&ccnet_proc_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CcnetProcClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_proc_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetProc), 0, (GInstanceInitFunc) ccnet_proc_instance_init, NULL };
		GType ccnet_proc_type_id;
		ccnet_proc_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetProc", &g_define_type_info, 0);
		g_once_init_leave (&ccnet_proc_type_id__volatile, ccnet_proc_type_id);
	}
	return ccnet_proc_type_id__volatile;
}


static void _vala_ccnet_proc_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CcnetProc * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_PROC, CcnetProc);
	switch (property_id) {
		case CCNET_PROC_PEER_NAME:
		g_value_set_string (value, ccnet_proc_get_peer_name (self));
		break;
		case CCNET_PROC_NAME:
		g_value_set_string (value, ccnet_proc_get_name (self));
		break;
		case CCNET_PROC_CTIME:
		g_value_set_int (value, ccnet_proc_get_ctime (self));
		break;
		case CCNET_PROC_DTIME:
		g_value_set_int (value, ccnet_proc_get_dtime (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_ccnet_proc_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CcnetProc * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_PROC, CcnetProc);
	switch (property_id) {
		case CCNET_PROC_PEER_NAME:
		ccnet_proc_set_peer_name (self, g_value_get_string (value));
		break;
		case CCNET_PROC_NAME:
		ccnet_proc_set_name (self, g_value_get_string (value));
		break;
		case CCNET_PROC_CTIME:
		ccnet_proc_set_ctime (self, g_value_get_int (value));
		break;
		case CCNET_PROC_DTIME:
		ccnet_proc_set_dtime (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


CcnetEmailUser* ccnet_email_user_construct (GType object_type) {
	CcnetEmailUser * self = NULL;
	self = (CcnetEmailUser*) g_object_new (object_type, NULL);
	return self;
}


CcnetEmailUser* ccnet_email_user_new (void) {
	return ccnet_email_user_construct (CCNET_TYPE_EMAIL_USER);
}


gint ccnet_email_user_get_id (CcnetEmailUser* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}


void ccnet_email_user_set_id (CcnetEmailUser* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_id = _tmp0_;
	g_object_notify ((GObject *) self, "id");
}


const gchar* ccnet_email_user_get_email (CcnetEmailUser* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_email;
	result = _tmp0_;
	return result;
}


void ccnet_email_user_set_email (CcnetEmailUser* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_email);
	self->priv->_email = _tmp1_;
	g_object_notify ((GObject *) self, "email");
}


gboolean ccnet_email_user_get_is_staff (CcnetEmailUser* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_is_staff;
	result = _tmp0_;
	return result;
}


void ccnet_email_user_set_is_staff (CcnetEmailUser* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_is_staff = _tmp0_;
	g_object_notify ((GObject *) self, "is-staff");
}


gboolean ccnet_email_user_get_is_active (CcnetEmailUser* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_is_active;
	result = _tmp0_;
	return result;
}


void ccnet_email_user_set_is_active (CcnetEmailUser* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_is_active = _tmp0_;
	g_object_notify ((GObject *) self, "is-active");
}


gint64 ccnet_email_user_get_ctime (CcnetEmailUser* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_ctime;
	result = _tmp0_;
	return result;
}


void ccnet_email_user_set_ctime (CcnetEmailUser* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_ctime = _tmp0_;
	g_object_notify ((GObject *) self, "ctime");
}


const gchar* ccnet_email_user_get_source (CcnetEmailUser* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_source;
	result = _tmp0_;
	return result;
}


void ccnet_email_user_set_source (CcnetEmailUser* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_source);
	self->priv->_source = _tmp1_;
	g_object_notify ((GObject *) self, "source");
}


const gchar* ccnet_email_user_get_role (CcnetEmailUser* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_role;
	result = _tmp0_;
	return result;
}


void ccnet_email_user_set_role (CcnetEmailUser* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_role);
	self->priv->_role = _tmp1_;
	g_object_notify ((GObject *) self, "role");
}


const gchar* ccnet_email_user_get_password (CcnetEmailUser* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_password;
	result = _tmp0_;
	return result;
}


void ccnet_email_user_set_password (CcnetEmailUser* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_password);
	self->priv->_password = _tmp1_;
	g_object_notify ((GObject *) self, "password");
}


static void ccnet_email_user_class_init (CcnetEmailUserClass * klass) {
	ccnet_email_user_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CcnetEmailUserPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_email_user_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_email_user_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_email_user_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_ID, g_param_spec_int ("id", "id", "id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_EMAIL, g_param_spec_string ("email", "email", "email", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_IS_STAFF, g_param_spec_boolean ("is-staff", "is-staff", "is-staff", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_IS_ACTIVE, g_param_spec_boolean ("is-active", "is-active", "is-active", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_CTIME, g_param_spec_int64 ("ctime", "ctime", "ctime", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_SOURCE, g_param_spec_string ("source", "source", "source", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_ROLE, g_param_spec_string ("role", "role", "role", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_EMAIL_USER_PASSWORD, g_param_spec_string ("password", "password", "password", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void ccnet_email_user_instance_init (CcnetEmailUser * self) {
	self->priv = CCNET_EMAIL_USER_GET_PRIVATE (self);
}


static void ccnet_email_user_finalize (GObject* obj) {
	CcnetEmailUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_EMAIL_USER, CcnetEmailUser);
	_g_free0 (self->priv->_email);
	_g_free0 (self->priv->_source);
	_g_free0 (self->priv->_role);
	_g_free0 (self->priv->_password);
	G_OBJECT_CLASS (ccnet_email_user_parent_class)->finalize (obj);
}


GType ccnet_email_user_get_type (void) {
	static volatile gsize ccnet_email_user_type_id__volatile = 0;
	if (g_once_init_enter (&ccnet_email_user_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CcnetEmailUserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_email_user_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetEmailUser), 0, (GInstanceInitFunc) ccnet_email_user_instance_init, NULL };
		GType ccnet_email_user_type_id;
		ccnet_email_user_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetEmailUser", &g_define_type_info, 0);
		g_once_init_leave (&ccnet_email_user_type_id__volatile, ccnet_email_user_type_id);
	}
	return ccnet_email_user_type_id__volatile;
}


static void _vala_ccnet_email_user_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CcnetEmailUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_EMAIL_USER, CcnetEmailUser);
	switch (property_id) {
		case CCNET_EMAIL_USER_ID:
		g_value_set_int (value, ccnet_email_user_get_id (self));
		break;
		case CCNET_EMAIL_USER_EMAIL:
		g_value_set_string (value, ccnet_email_user_get_email (self));
		break;
		case CCNET_EMAIL_USER_IS_STAFF:
		g_value_set_boolean (value, ccnet_email_user_get_is_staff (self));
		break;
		case CCNET_EMAIL_USER_IS_ACTIVE:
		g_value_set_boolean (value, ccnet_email_user_get_is_active (self));
		break;
		case CCNET_EMAIL_USER_CTIME:
		g_value_set_int64 (value, ccnet_email_user_get_ctime (self));
		break;
		case CCNET_EMAIL_USER_SOURCE:
		g_value_set_string (value, ccnet_email_user_get_source (self));
		break;
		case CCNET_EMAIL_USER_ROLE:
		g_value_set_string (value, ccnet_email_user_get_role (self));
		break;
		case CCNET_EMAIL_USER_PASSWORD:
		g_value_set_string (value, ccnet_email_user_get_password (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_ccnet_email_user_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CcnetEmailUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_EMAIL_USER, CcnetEmailUser);
	switch (property_id) {
		case CCNET_EMAIL_USER_ID:
		ccnet_email_user_set_id (self, g_value_get_int (value));
		break;
		case CCNET_EMAIL_USER_EMAIL:
		ccnet_email_user_set_email (self, g_value_get_string (value));
		break;
		case CCNET_EMAIL_USER_IS_STAFF:
		ccnet_email_user_set_is_staff (self, g_value_get_boolean (value));
		break;
		case CCNET_EMAIL_USER_IS_ACTIVE:
		ccnet_email_user_set_is_active (self, g_value_get_boolean (value));
		break;
		case CCNET_EMAIL_USER_CTIME:
		ccnet_email_user_set_ctime (self, g_value_get_int64 (value));
		break;
		case CCNET_EMAIL_USER_SOURCE:
		ccnet_email_user_set_source (self, g_value_get_string (value));
		break;
		case CCNET_EMAIL_USER_ROLE:
		ccnet_email_user_set_role (self, g_value_get_string (value));
		break;
		case CCNET_EMAIL_USER_PASSWORD:
		ccnet_email_user_set_password (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


CcnetGroup* ccnet_group_construct (GType object_type) {
	CcnetGroup * self = NULL;
	self = (CcnetGroup*) g_object_new (object_type, NULL);
	return self;
}


CcnetGroup* ccnet_group_new (void) {
	return ccnet_group_construct (CCNET_TYPE_GROUP);
}


gint ccnet_group_get_id (CcnetGroup* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}


void ccnet_group_set_id (CcnetGroup* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_id = _tmp0_;
	g_object_notify ((GObject *) self, "id");
}


const gchar* ccnet_group_get_group_name (CcnetGroup* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_group_name;
	result = _tmp0_;
	return result;
}


void ccnet_group_set_group_name (CcnetGroup* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_group_name);
	self->priv->_group_name = _tmp1_;
	g_object_notify ((GObject *) self, "group-name");
}


const gchar* ccnet_group_get_creator_name (CcnetGroup* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_creator_name;
	result = _tmp0_;
	return result;
}


void ccnet_group_set_creator_name (CcnetGroup* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_creator_name);
	self->priv->_creator_name = _tmp1_;
	g_object_notify ((GObject *) self, "creator-name");
}


gint64 ccnet_group_get_timestamp (CcnetGroup* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_timestamp;
	result = _tmp0_;
	return result;
}


void ccnet_group_set_timestamp (CcnetGroup* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_timestamp = _tmp0_;
	g_object_notify ((GObject *) self, "timestamp");
}


const gchar* ccnet_group_get_source (CcnetGroup* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_source;
	result = _tmp0_;
	return result;
}


void ccnet_group_set_source (CcnetGroup* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_source);
	self->priv->_source = _tmp1_;
	g_object_notify ((GObject *) self, "source");
}


static void ccnet_group_class_init (CcnetGroupClass * klass) {
	ccnet_group_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CcnetGroupPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_group_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_group_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_group_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_ID, g_param_spec_int ("id", "id", "id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_GROUP_NAME, g_param_spec_string ("group-name", "group-name", "group-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_CREATOR_NAME, g_param_spec_string ("creator-name", "creator-name", "creator-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_TIMESTAMP, g_param_spec_int64 ("timestamp", "timestamp", "timestamp", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_SOURCE, g_param_spec_string ("source", "source", "source", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void ccnet_group_instance_init (CcnetGroup * self) {
	self->priv = CCNET_GROUP_GET_PRIVATE (self);
}


static void ccnet_group_finalize (GObject* obj) {
	CcnetGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_GROUP, CcnetGroup);
	_g_free0 (self->priv->_group_name);
	_g_free0 (self->priv->_creator_name);
	_g_free0 (self->priv->_source);
	G_OBJECT_CLASS (ccnet_group_parent_class)->finalize (obj);
}


GType ccnet_group_get_type (void) {
	static volatile gsize ccnet_group_type_id__volatile = 0;
	if (g_once_init_enter (&ccnet_group_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CcnetGroupClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_group_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetGroup), 0, (GInstanceInitFunc) ccnet_group_instance_init, NULL };
		GType ccnet_group_type_id;
		ccnet_group_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetGroup", &g_define_type_info, 0);
		g_once_init_leave (&ccnet_group_type_id__volatile, ccnet_group_type_id);
	}
	return ccnet_group_type_id__volatile;
}


static void _vala_ccnet_group_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CcnetGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_GROUP, CcnetGroup);
	switch (property_id) {
		case CCNET_GROUP_ID:
		g_value_set_int (value, ccnet_group_get_id (self));
		break;
		case CCNET_GROUP_GROUP_NAME:
		g_value_set_string (value, ccnet_group_get_group_name (self));
		break;
		case CCNET_GROUP_CREATOR_NAME:
		g_value_set_string (value, ccnet_group_get_creator_name (self));
		break;
		case CCNET_GROUP_TIMESTAMP:
		g_value_set_int64 (value, ccnet_group_get_timestamp (self));
		break;
		case CCNET_GROUP_SOURCE:
		g_value_set_string (value, ccnet_group_get_source (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_ccnet_group_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CcnetGroup * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_GROUP, CcnetGroup);
	switch (property_id) {
		case CCNET_GROUP_ID:
		ccnet_group_set_id (self, g_value_get_int (value));
		break;
		case CCNET_GROUP_GROUP_NAME:
		ccnet_group_set_group_name (self, g_value_get_string (value));
		break;
		case CCNET_GROUP_CREATOR_NAME:
		ccnet_group_set_creator_name (self, g_value_get_string (value));
		break;
		case CCNET_GROUP_TIMESTAMP:
		ccnet_group_set_timestamp (self, g_value_get_int64 (value));
		break;
		case CCNET_GROUP_SOURCE:
		ccnet_group_set_source (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


CcnetGroupUser* ccnet_group_user_construct (GType object_type) {
	CcnetGroupUser * self = NULL;
	self = (CcnetGroupUser*) g_object_new (object_type, NULL);
	return self;
}


CcnetGroupUser* ccnet_group_user_new (void) {
	return ccnet_group_user_construct (CCNET_TYPE_GROUP_USER);
}


gint ccnet_group_user_get_group_id (CcnetGroupUser* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_group_id;
	result = _tmp0_;
	return result;
}


void ccnet_group_user_set_group_id (CcnetGroupUser* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_group_id = _tmp0_;
	g_object_notify ((GObject *) self, "group-id");
}


const gchar* ccnet_group_user_get_user_name (CcnetGroupUser* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_user_name;
	result = _tmp0_;
	return result;
}


void ccnet_group_user_set_user_name (CcnetGroupUser* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_user_name);
	self->priv->_user_name = _tmp1_;
	g_object_notify ((GObject *) self, "user-name");
}


gint ccnet_group_user_get_is_staff (CcnetGroupUser* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_is_staff;
	result = _tmp0_;
	return result;
}


void ccnet_group_user_set_is_staff (CcnetGroupUser* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_is_staff = _tmp0_;
	g_object_notify ((GObject *) self, "is-staff");
}


static void ccnet_group_user_class_init (CcnetGroupUserClass * klass) {
	ccnet_group_user_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CcnetGroupUserPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_group_user_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_group_user_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_group_user_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_USER_GROUP_ID, g_param_spec_int ("group-id", "group-id", "group-id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_USER_USER_NAME, g_param_spec_string ("user-name", "user-name", "user-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_GROUP_USER_IS_STAFF, g_param_spec_int ("is-staff", "is-staff", "is-staff", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void ccnet_group_user_instance_init (CcnetGroupUser * self) {
	self->priv = CCNET_GROUP_USER_GET_PRIVATE (self);
}


static void ccnet_group_user_finalize (GObject* obj) {
	CcnetGroupUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_GROUP_USER, CcnetGroupUser);
	_g_free0 (self->priv->_user_name);
	G_OBJECT_CLASS (ccnet_group_user_parent_class)->finalize (obj);
}


GType ccnet_group_user_get_type (void) {
	static volatile gsize ccnet_group_user_type_id__volatile = 0;
	if (g_once_init_enter (&ccnet_group_user_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CcnetGroupUserClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_group_user_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetGroupUser), 0, (GInstanceInitFunc) ccnet_group_user_instance_init, NULL };
		GType ccnet_group_user_type_id;
		ccnet_group_user_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetGroupUser", &g_define_type_info, 0);
		g_once_init_leave (&ccnet_group_user_type_id__volatile, ccnet_group_user_type_id);
	}
	return ccnet_group_user_type_id__volatile;
}


static void _vala_ccnet_group_user_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CcnetGroupUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_GROUP_USER, CcnetGroupUser);
	switch (property_id) {
		case CCNET_GROUP_USER_GROUP_ID:
		g_value_set_int (value, ccnet_group_user_get_group_id (self));
		break;
		case CCNET_GROUP_USER_USER_NAME:
		g_value_set_string (value, ccnet_group_user_get_user_name (self));
		break;
		case CCNET_GROUP_USER_IS_STAFF:
		g_value_set_int (value, ccnet_group_user_get_is_staff (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_ccnet_group_user_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CcnetGroupUser * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_GROUP_USER, CcnetGroupUser);
	switch (property_id) {
		case CCNET_GROUP_USER_GROUP_ID:
		ccnet_group_user_set_group_id (self, g_value_get_int (value));
		break;
		case CCNET_GROUP_USER_USER_NAME:
		ccnet_group_user_set_user_name (self, g_value_get_string (value));
		break;
		case CCNET_GROUP_USER_IS_STAFF:
		ccnet_group_user_set_is_staff (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


CcnetOrganization* ccnet_organization_construct (GType object_type) {
	CcnetOrganization * self = NULL;
	self = (CcnetOrganization*) g_object_new (object_type, NULL);
	return self;
}


CcnetOrganization* ccnet_organization_new (void) {
	return ccnet_organization_construct (CCNET_TYPE_ORGANIZATION);
}


gint ccnet_organization_get_org_id (CcnetOrganization* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_org_id;
	result = _tmp0_;
	return result;
}


void ccnet_organization_set_org_id (CcnetOrganization* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_org_id = _tmp0_;
	g_object_notify ((GObject *) self, "org-id");
}


const gchar* ccnet_organization_get_email (CcnetOrganization* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_email;
	result = _tmp0_;
	return result;
}


void ccnet_organization_set_email (CcnetOrganization* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_email);
	self->priv->_email = _tmp1_;
	g_object_notify ((GObject *) self, "email");
}


gint ccnet_organization_get_is_staff (CcnetOrganization* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_is_staff;
	result = _tmp0_;
	return result;
}


void ccnet_organization_set_is_staff (CcnetOrganization* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_is_staff = _tmp0_;
	g_object_notify ((GObject *) self, "is-staff");
}


const gchar* ccnet_organization_get_org_name (CcnetOrganization* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_org_name;
	result = _tmp0_;
	return result;
}


void ccnet_organization_set_org_name (CcnetOrganization* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_org_name);
	self->priv->_org_name = _tmp1_;
	g_object_notify ((GObject *) self, "org-name");
}


const gchar* ccnet_organization_get_url_prefix (CcnetOrganization* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_url_prefix;
	result = _tmp0_;
	return result;
}


void ccnet_organization_set_url_prefix (CcnetOrganization* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_url_prefix);
	self->priv->_url_prefix = _tmp1_;
	g_object_notify ((GObject *) self, "url-prefix");
}


const gchar* ccnet_organization_get_creator (CcnetOrganization* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_creator;
	result = _tmp0_;
	return result;
}


void ccnet_organization_set_creator (CcnetOrganization* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_creator);
	self->priv->_creator = _tmp1_;
	g_object_notify ((GObject *) self, "creator");
}


gint64 ccnet_organization_get_ctime (CcnetOrganization* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_ctime;
	result = _tmp0_;
	return result;
}


void ccnet_organization_set_ctime (CcnetOrganization* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_ctime = _tmp0_;
	g_object_notify ((GObject *) self, "ctime");
}


static void ccnet_organization_class_init (CcnetOrganizationClass * klass) {
	ccnet_organization_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CcnetOrganizationPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_organization_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_organization_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_organization_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_ORG_ID, g_param_spec_int ("org-id", "org-id", "org-id", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_EMAIL, g_param_spec_string ("email", "email", "email", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_IS_STAFF, g_param_spec_int ("is-staff", "is-staff", "is-staff", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_ORG_NAME, g_param_spec_string ("org-name", "org-name", "org-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_URL_PREFIX, g_param_spec_string ("url-prefix", "url-prefix", "url-prefix", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_CREATOR, g_param_spec_string ("creator", "creator", "creator", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_ORGANIZATION_CTIME, g_param_spec_int64 ("ctime", "ctime", "ctime", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void ccnet_organization_instance_init (CcnetOrganization * self) {
	self->priv = CCNET_ORGANIZATION_GET_PRIVATE (self);
}


static void ccnet_organization_finalize (GObject* obj) {
	CcnetOrganization * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_ORGANIZATION, CcnetOrganization);
	_g_free0 (self->priv->_email);
	_g_free0 (self->priv->_org_name);
	_g_free0 (self->priv->_url_prefix);
	_g_free0 (self->priv->_creator);
	G_OBJECT_CLASS (ccnet_organization_parent_class)->finalize (obj);
}


GType ccnet_organization_get_type (void) {
	static volatile gsize ccnet_organization_type_id__volatile = 0;
	if (g_once_init_enter (&ccnet_organization_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CcnetOrganizationClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_organization_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetOrganization), 0, (GInstanceInitFunc) ccnet_organization_instance_init, NULL };
		GType ccnet_organization_type_id;
		ccnet_organization_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetOrganization", &g_define_type_info, 0);
		g_once_init_leave (&ccnet_organization_type_id__volatile, ccnet_organization_type_id);
	}
	return ccnet_organization_type_id__volatile;
}


static void _vala_ccnet_organization_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CcnetOrganization * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_ORGANIZATION, CcnetOrganization);
	switch (property_id) {
		case CCNET_ORGANIZATION_ORG_ID:
		g_value_set_int (value, ccnet_organization_get_org_id (self));
		break;
		case CCNET_ORGANIZATION_EMAIL:
		g_value_set_string (value, ccnet_organization_get_email (self));
		break;
		case CCNET_ORGANIZATION_IS_STAFF:
		g_value_set_int (value, ccnet_organization_get_is_staff (self));
		break;
		case CCNET_ORGANIZATION_ORG_NAME:
		g_value_set_string (value, ccnet_organization_get_org_name (self));
		break;
		case CCNET_ORGANIZATION_URL_PREFIX:
		g_value_set_string (value, ccnet_organization_get_url_prefix (self));
		break;
		case CCNET_ORGANIZATION_CREATOR:
		g_value_set_string (value, ccnet_organization_get_creator (self));
		break;
		case CCNET_ORGANIZATION_CTIME:
		g_value_set_int64 (value, ccnet_organization_get_ctime (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_ccnet_organization_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CcnetOrganization * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_ORGANIZATION, CcnetOrganization);
	switch (property_id) {
		case CCNET_ORGANIZATION_ORG_ID:
		ccnet_organization_set_org_id (self, g_value_get_int (value));
		break;
		case CCNET_ORGANIZATION_EMAIL:
		ccnet_organization_set_email (self, g_value_get_string (value));
		break;
		case CCNET_ORGANIZATION_IS_STAFF:
		ccnet_organization_set_is_staff (self, g_value_get_int (value));
		break;
		case CCNET_ORGANIZATION_ORG_NAME:
		ccnet_organization_set_org_name (self, g_value_get_string (value));
		break;
		case CCNET_ORGANIZATION_URL_PREFIX:
		ccnet_organization_set_url_prefix (self, g_value_get_string (value));
		break;
		case CCNET_ORGANIZATION_CREATOR:
		ccnet_organization_set_creator (self, g_value_get_string (value));
		break;
		case CCNET_ORGANIZATION_CTIME:
		ccnet_organization_set_ctime (self, g_value_get_int64 (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


CcnetPeerStat* ccnet_peer_stat_construct (GType object_type) {
	CcnetPeerStat * self = NULL;
	self = (CcnetPeerStat*) g_object_new (object_type, NULL);
	return self;
}


CcnetPeerStat* ccnet_peer_stat_new (void) {
	return ccnet_peer_stat_construct (CCNET_TYPE_PEER_STAT);
}


const gchar* ccnet_peer_stat_get_id (CcnetPeerStat* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_id;
	result = _tmp0_;
	return result;
}


void ccnet_peer_stat_set_id (CcnetPeerStat* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_id);
	self->priv->_id = _tmp1_;
	g_object_notify ((GObject *) self, "id");
}


const gchar* ccnet_peer_stat_get_name (CcnetPeerStat* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


void ccnet_peer_stat_set_name (CcnetPeerStat* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


const gchar* ccnet_peer_stat_get_ip (CcnetPeerStat* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_ip;
	result = _tmp0_;
	return result;
}


void ccnet_peer_stat_set_ip (CcnetPeerStat* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_ip);
	self->priv->_ip = _tmp1_;
	g_object_notify ((GObject *) self, "ip");
}


gboolean ccnet_peer_stat_get_encrypt (CcnetPeerStat* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_encrypt;
	result = _tmp0_;
	return result;
}


void ccnet_peer_stat_set_encrypt (CcnetPeerStat* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_encrypt = _tmp0_;
	g_object_notify ((GObject *) self, "encrypt");
}


gint64 ccnet_peer_stat_get_last_up (CcnetPeerStat* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_last_up;
	result = _tmp0_;
	return result;
}


void ccnet_peer_stat_set_last_up (CcnetPeerStat* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_last_up = _tmp0_;
	g_object_notify ((GObject *) self, "last-up");
}


gint ccnet_peer_stat_get_proc_num (CcnetPeerStat* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_proc_num;
	result = _tmp0_;
	return result;
}


void ccnet_peer_stat_set_proc_num (CcnetPeerStat* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_proc_num = _tmp0_;
	g_object_notify ((GObject *) self, "proc-num");
}


static void ccnet_peer_stat_class_init (CcnetPeerStatClass * klass) {
	ccnet_peer_stat_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CcnetPeerStatPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_ccnet_peer_stat_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_ccnet_peer_stat_set_property;
	G_OBJECT_CLASS (klass)->finalize = ccnet_peer_stat_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PEER_STAT_ID, g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PEER_STAT_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PEER_STAT_IP, g_param_spec_string ("ip", "ip", "ip", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PEER_STAT_ENCRYPT, g_param_spec_boolean ("encrypt", "encrypt", "encrypt", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PEER_STAT_LAST_UP, g_param_spec_int64 ("last-up", "last-up", "last-up", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CCNET_PEER_STAT_PROC_NUM, g_param_spec_int ("proc-num", "proc-num", "proc-num", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void ccnet_peer_stat_instance_init (CcnetPeerStat * self) {
	self->priv = CCNET_PEER_STAT_GET_PRIVATE (self);
}


static void ccnet_peer_stat_finalize (GObject* obj) {
	CcnetPeerStat * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CCNET_TYPE_PEER_STAT, CcnetPeerStat);
	_g_free0 (self->priv->_id);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_ip);
	G_OBJECT_CLASS (ccnet_peer_stat_parent_class)->finalize (obj);
}


GType ccnet_peer_stat_get_type (void) {
	static volatile gsize ccnet_peer_stat_type_id__volatile = 0;
	if (g_once_init_enter (&ccnet_peer_stat_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CcnetPeerStatClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ccnet_peer_stat_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CcnetPeerStat), 0, (GInstanceInitFunc) ccnet_peer_stat_instance_init, NULL };
		GType ccnet_peer_stat_type_id;
		ccnet_peer_stat_type_id = g_type_register_static (G_TYPE_OBJECT, "CcnetPeerStat", &g_define_type_info, 0);
		g_once_init_leave (&ccnet_peer_stat_type_id__volatile, ccnet_peer_stat_type_id);
	}
	return ccnet_peer_stat_type_id__volatile;
}


static void _vala_ccnet_peer_stat_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CcnetPeerStat * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_PEER_STAT, CcnetPeerStat);
	switch (property_id) {
		case CCNET_PEER_STAT_ID:
		g_value_set_string (value, ccnet_peer_stat_get_id (self));
		break;
		case CCNET_PEER_STAT_NAME:
		g_value_set_string (value, ccnet_peer_stat_get_name (self));
		break;
		case CCNET_PEER_STAT_IP:
		g_value_set_string (value, ccnet_peer_stat_get_ip (self));
		break;
		case CCNET_PEER_STAT_ENCRYPT:
		g_value_set_boolean (value, ccnet_peer_stat_get_encrypt (self));
		break;
		case CCNET_PEER_STAT_LAST_UP:
		g_value_set_int64 (value, ccnet_peer_stat_get_last_up (self));
		break;
		case CCNET_PEER_STAT_PROC_NUM:
		g_value_set_int (value, ccnet_peer_stat_get_proc_num (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_ccnet_peer_stat_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CcnetPeerStat * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CCNET_TYPE_PEER_STAT, CcnetPeerStat);
	switch (property_id) {
		case CCNET_PEER_STAT_ID:
		ccnet_peer_stat_set_id (self, g_value_get_string (value));
		break;
		case CCNET_PEER_STAT_NAME:
		ccnet_peer_stat_set_name (self, g_value_get_string (value));
		break;
		case CCNET_PEER_STAT_IP:
		ccnet_peer_stat_set_ip (self, g_value_get_string (value));
		break;
		case CCNET_PEER_STAT_ENCRYPT:
		ccnet_peer_stat_set_encrypt (self, g_value_get_boolean (value));
		break;
		case CCNET_PEER_STAT_LAST_UP:
		ccnet_peer_stat_set_last_up (self, g_value_get_int64 (value));
		break;
		case CCNET_PEER_STAT_PROC_NUM:
		ccnet_peer_stat_set_proc_num (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



