/* commit.c generated by valac 0.34.4, the Vala compiler
 * generated from commit.vala, do not modify */

/* compile this file with `valac --pkg posix repo.vala -C -H repo.h`*/

#include <glib.h>
#include <glib-object.h>
#include <string.h>


#define SEAFILE_TYPE_COMMIT (seafile_commit_get_type ())
#define SEAFILE_COMMIT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_COMMIT, SeafileCommit))
#define SEAFILE_COMMIT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_COMMIT, SeafileCommitClass))
#define SEAFILE_IS_COMMIT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_COMMIT))
#define SEAFILE_IS_COMMIT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_COMMIT))
#define SEAFILE_COMMIT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_COMMIT, SeafileCommitClass))

typedef struct _SeafileCommit SeafileCommit;
typedef struct _SeafileCommitClass SeafileCommitClass;
typedef struct _SeafileCommitPrivate SeafileCommitPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SeafileCommit {
	GObject parent_instance;
	SeafileCommitPrivate * priv;
	gchar _id[41];
	gchar* _creator;
	gchar* _desc;
	gint64 _ctime;
	gchar* _repo_id;
	gchar* _root_id;
};

struct _SeafileCommitClass {
	GObjectClass parent_class;
};

struct _SeafileCommitPrivate {
	gchar* _creator_name;
	gchar* _parent_id;
	gchar* _second_parent_id;
	gint _version;
	gboolean _new_merge;
	gboolean _conflict;
	gchar* _rev_file_id;
	gint64 _rev_file_size;
	gchar* _rev_renamed_old_path;
	gchar* _device_name;
};


static gpointer seafile_commit_parent_class = NULL;

GType seafile_commit_get_type (void) G_GNUC_CONST;
#define SEAFILE_COMMIT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_COMMIT, SeafileCommitPrivate))
enum  {
	SEAFILE_COMMIT_DUMMY_PROPERTY,
	SEAFILE_COMMIT_ID,
	SEAFILE_COMMIT_CREATOR_NAME,
	SEAFILE_COMMIT_CREATOR,
	SEAFILE_COMMIT_DESC,
	SEAFILE_COMMIT_CTIME,
	SEAFILE_COMMIT_PARENT_ID,
	SEAFILE_COMMIT_SECOND_PARENT_ID,
	SEAFILE_COMMIT_REPO_ID,
	SEAFILE_COMMIT_ROOT_ID,
	SEAFILE_COMMIT_VERSION,
	SEAFILE_COMMIT_NEW_MERGE,
	SEAFILE_COMMIT_CONFLICT,
	SEAFILE_COMMIT_REV_FILE_ID,
	SEAFILE_COMMIT_REV_FILE_SIZE,
	SEAFILE_COMMIT_REV_RENAMED_OLD_PATH,
	SEAFILE_COMMIT_DEVICE_NAME
};
SeafileCommit* seafile_commit_new (void);
SeafileCommit* seafile_commit_construct (GType object_type);
const gchar* seafile_commit_get_id (SeafileCommit* self);
void seafile_commit_set_id (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_creator_name (SeafileCommit* self);
void seafile_commit_set_creator_name (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_creator (SeafileCommit* self);
void seafile_commit_set_creator (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_desc (SeafileCommit* self);
void seafile_commit_set_desc (SeafileCommit* self, const gchar* value);
gint64 seafile_commit_get_ctime (SeafileCommit* self);
void seafile_commit_set_ctime (SeafileCommit* self, gint64 value);
const gchar* seafile_commit_get_parent_id (SeafileCommit* self);
void seafile_commit_set_parent_id (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_second_parent_id (SeafileCommit* self);
void seafile_commit_set_second_parent_id (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_repo_id (SeafileCommit* self);
void seafile_commit_set_repo_id (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_root_id (SeafileCommit* self);
void seafile_commit_set_root_id (SeafileCommit* self, const gchar* value);
gint seafile_commit_get_version (SeafileCommit* self);
void seafile_commit_set_version (SeafileCommit* self, gint value);
gboolean seafile_commit_get_new_merge (SeafileCommit* self);
void seafile_commit_set_new_merge (SeafileCommit* self, gboolean value);
gboolean seafile_commit_get_conflict (SeafileCommit* self);
void seafile_commit_set_conflict (SeafileCommit* self, gboolean value);
const gchar* seafile_commit_get_rev_file_id (SeafileCommit* self);
void seafile_commit_set_rev_file_id (SeafileCommit* self, const gchar* value);
gint64 seafile_commit_get_rev_file_size (SeafileCommit* self);
void seafile_commit_set_rev_file_size (SeafileCommit* self, gint64 value);
const gchar* seafile_commit_get_rev_renamed_old_path (SeafileCommit* self);
void seafile_commit_set_rev_renamed_old_path (SeafileCommit* self, const gchar* value);
const gchar* seafile_commit_get_device_name (SeafileCommit* self);
void seafile_commit_set_device_name (SeafileCommit* self, const gchar* value);
static void seafile_commit_finalize (GObject* obj);
static void _vala_seafile_commit_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_commit_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SeafileCommit* seafile_commit_construct (GType object_type) {
	SeafileCommit * self = NULL;
	self = (SeafileCommit*) g_object_new (object_type, NULL);
	return self;
}


SeafileCommit* seafile_commit_new (void) {
	return seafile_commit_construct (SEAFILE_TYPE_COMMIT);
}


const gchar* seafile_commit_get_id (SeafileCommit* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = (const gchar*) self->_id;
	return result;
}


void seafile_commit_set_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar _tmp1_ = '\0';
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	memcpy (self->_id, _tmp0_, (gsize) 40);
	self->_id[40] = '\0';
	_tmp1_ = self->_id[40];
	g_object_notify ((GObject *) self, "id");
}


const gchar* seafile_commit_get_creator_name (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_creator_name;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_creator_name (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_creator_name);
	self->priv->_creator_name = _tmp1_;
	g_object_notify ((GObject *) self, "creator-name");
}


const gchar* seafile_commit_get_creator (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_creator;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_creator (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_creator);
	self->_creator = _tmp1_;
	g_object_notify ((GObject *) self, "creator");
}


const gchar* seafile_commit_get_desc (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_desc;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_desc (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_desc);
	self->_desc = _tmp1_;
	g_object_notify ((GObject *) self, "desc");
}


gint64 seafile_commit_get_ctime (SeafileCommit* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->_ctime;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_ctime (SeafileCommit* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->_ctime = _tmp0_;
	g_object_notify ((GObject *) self, "ctime");
}


const gchar* seafile_commit_get_parent_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_parent_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_parent_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_parent_id);
	self->priv->_parent_id = _tmp1_;
	g_object_notify ((GObject *) self, "parent-id");
}


const gchar* seafile_commit_get_second_parent_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_second_parent_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_second_parent_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_second_parent_id);
	self->priv->_second_parent_id = _tmp1_;
	g_object_notify ((GObject *) self, "second-parent-id");
}


const gchar* seafile_commit_get_repo_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_repo_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_repo_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_repo_id);
	self->_repo_id = _tmp1_;
	g_object_notify ((GObject *) self, "repo-id");
}


const gchar* seafile_commit_get_root_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->_root_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_root_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->_root_id);
	self->_root_id = _tmp1_;
	g_object_notify ((GObject *) self, "root-id");
}


gint seafile_commit_get_version (SeafileCommit* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_version;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_version (SeafileCommit* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_version = _tmp0_;
	g_object_notify ((GObject *) self, "version");
}


gboolean seafile_commit_get_new_merge (SeafileCommit* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_new_merge;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_new_merge (SeafileCommit* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_new_merge = _tmp0_;
	g_object_notify ((GObject *) self, "new-merge");
}


gboolean seafile_commit_get_conflict (SeafileCommit* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_conflict;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_conflict (SeafileCommit* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_conflict = _tmp0_;
	g_object_notify ((GObject *) self, "conflict");
}


const gchar* seafile_commit_get_rev_file_id (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_rev_file_id;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_rev_file_id (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_rev_file_id);
	self->priv->_rev_file_id = _tmp1_;
	g_object_notify ((GObject *) self, "rev-file-id");
}


gint64 seafile_commit_get_rev_file_size (SeafileCommit* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_rev_file_size;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_rev_file_size (SeafileCommit* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_rev_file_size = _tmp0_;
	g_object_notify ((GObject *) self, "rev-file-size");
}


const gchar* seafile_commit_get_rev_renamed_old_path (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_rev_renamed_old_path;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_rev_renamed_old_path (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_rev_renamed_old_path);
	self->priv->_rev_renamed_old_path = _tmp1_;
	g_object_notify ((GObject *) self, "rev-renamed-old-path");
}


const gchar* seafile_commit_get_device_name (SeafileCommit* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_device_name;
	result = _tmp0_;
	return result;
}


void seafile_commit_set_device_name (SeafileCommit* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_device_name);
	self->priv->_device_name = _tmp1_;
	g_object_notify ((GObject *) self, "device-name");
}


static void seafile_commit_class_init (SeafileCommitClass * klass) {
	seafile_commit_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileCommitPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_commit_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_commit_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_commit_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_ID, g_param_spec_string ("id", "id", "id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_CREATOR_NAME, g_param_spec_string ("creator-name", "creator-name", "creator-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_CREATOR, g_param_spec_string ("creator", "creator", "creator", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_DESC, g_param_spec_string ("desc", "desc", "desc", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_CTIME, g_param_spec_int64 ("ctime", "ctime", "ctime", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_PARENT_ID, g_param_spec_string ("parent-id", "parent-id", "parent-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_SECOND_PARENT_ID, g_param_spec_string ("second-parent-id", "second-parent-id", "second-parent-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_REPO_ID, g_param_spec_string ("repo-id", "repo-id", "repo-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_ROOT_ID, g_param_spec_string ("root-id", "root-id", "root-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_VERSION, g_param_spec_int ("version", "version", "version", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_NEW_MERGE, g_param_spec_boolean ("new-merge", "new-merge", "new-merge", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_CONFLICT, g_param_spec_boolean ("conflict", "conflict", "conflict", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_REV_FILE_ID, g_param_spec_string ("rev-file-id", "rev-file-id", "rev-file-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_REV_FILE_SIZE, g_param_spec_int64 ("rev-file-size", "rev-file-size", "rev-file-size", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_REV_RENAMED_OLD_PATH, g_param_spec_string ("rev-renamed-old-path", "rev-renamed-old-path", "rev-renamed-old-path", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COMMIT_DEVICE_NAME, g_param_spec_string ("device-name", "device-name", "device-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_commit_instance_init (SeafileCommit * self) {
	self->priv = SEAFILE_COMMIT_GET_PRIVATE (self);
}


static void seafile_commit_finalize (GObject* obj) {
	SeafileCommit * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_COMMIT, SeafileCommit);
	_g_free0 (self->priv->_creator_name);
	_g_free0 (self->_creator);
	_g_free0 (self->_desc);
	_g_free0 (self->priv->_parent_id);
	_g_free0 (self->priv->_second_parent_id);
	_g_free0 (self->_repo_id);
	_g_free0 (self->_root_id);
	_g_free0 (self->priv->_rev_file_id);
	_g_free0 (self->priv->_rev_renamed_old_path);
	_g_free0 (self->priv->_device_name);
	G_OBJECT_CLASS (seafile_commit_parent_class)->finalize (obj);
}


GType seafile_commit_get_type (void) {
	static volatile gsize seafile_commit_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_commit_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileCommitClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_commit_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileCommit), 0, (GInstanceInitFunc) seafile_commit_instance_init, NULL };
		GType seafile_commit_type_id;
		seafile_commit_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileCommit", &g_define_type_info, 0);
		g_once_init_leave (&seafile_commit_type_id__volatile, seafile_commit_type_id);
	}
	return seafile_commit_type_id__volatile;
}


static void _vala_seafile_commit_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileCommit * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_COMMIT, SeafileCommit);
	switch (property_id) {
		case SEAFILE_COMMIT_ID:
		g_value_set_string (value, seafile_commit_get_id (self));
		break;
		case SEAFILE_COMMIT_CREATOR_NAME:
		g_value_set_string (value, seafile_commit_get_creator_name (self));
		break;
		case SEAFILE_COMMIT_CREATOR:
		g_value_set_string (value, seafile_commit_get_creator (self));
		break;
		case SEAFILE_COMMIT_DESC:
		g_value_set_string (value, seafile_commit_get_desc (self));
		break;
		case SEAFILE_COMMIT_CTIME:
		g_value_set_int64 (value, seafile_commit_get_ctime (self));
		break;
		case SEAFILE_COMMIT_PARENT_ID:
		g_value_set_string (value, seafile_commit_get_parent_id (self));
		break;
		case SEAFILE_COMMIT_SECOND_PARENT_ID:
		g_value_set_string (value, seafile_commit_get_second_parent_id (self));
		break;
		case SEAFILE_COMMIT_REPO_ID:
		g_value_set_string (value, seafile_commit_get_repo_id (self));
		break;
		case SEAFILE_COMMIT_ROOT_ID:
		g_value_set_string (value, seafile_commit_get_root_id (self));
		break;
		case SEAFILE_COMMIT_VERSION:
		g_value_set_int (value, seafile_commit_get_version (self));
		break;
		case SEAFILE_COMMIT_NEW_MERGE:
		g_value_set_boolean (value, seafile_commit_get_new_merge (self));
		break;
		case SEAFILE_COMMIT_CONFLICT:
		g_value_set_boolean (value, seafile_commit_get_conflict (self));
		break;
		case SEAFILE_COMMIT_REV_FILE_ID:
		g_value_set_string (value, seafile_commit_get_rev_file_id (self));
		break;
		case SEAFILE_COMMIT_REV_FILE_SIZE:
		g_value_set_int64 (value, seafile_commit_get_rev_file_size (self));
		break;
		case SEAFILE_COMMIT_REV_RENAMED_OLD_PATH:
		g_value_set_string (value, seafile_commit_get_rev_renamed_old_path (self));
		break;
		case SEAFILE_COMMIT_DEVICE_NAME:
		g_value_set_string (value, seafile_commit_get_device_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_commit_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileCommit * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_COMMIT, SeafileCommit);
	switch (property_id) {
		case SEAFILE_COMMIT_ID:
		seafile_commit_set_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_CREATOR_NAME:
		seafile_commit_set_creator_name (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_CREATOR:
		seafile_commit_set_creator (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_DESC:
		seafile_commit_set_desc (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_CTIME:
		seafile_commit_set_ctime (self, g_value_get_int64 (value));
		break;
		case SEAFILE_COMMIT_PARENT_ID:
		seafile_commit_set_parent_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_SECOND_PARENT_ID:
		seafile_commit_set_second_parent_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_REPO_ID:
		seafile_commit_set_repo_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_ROOT_ID:
		seafile_commit_set_root_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_VERSION:
		seafile_commit_set_version (self, g_value_get_int (value));
		break;
		case SEAFILE_COMMIT_NEW_MERGE:
		seafile_commit_set_new_merge (self, g_value_get_boolean (value));
		break;
		case SEAFILE_COMMIT_CONFLICT:
		seafile_commit_set_conflict (self, g_value_get_boolean (value));
		break;
		case SEAFILE_COMMIT_REV_FILE_ID:
		seafile_commit_set_rev_file_id (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_REV_FILE_SIZE:
		seafile_commit_set_rev_file_size (self, g_value_get_int64 (value));
		break;
		case SEAFILE_COMMIT_REV_RENAMED_OLD_PATH:
		seafile_commit_set_rev_renamed_old_path (self, g_value_get_string (value));
		break;
		case SEAFILE_COMMIT_DEVICE_NAME:
		seafile_commit_set_device_name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



