/* copy-task.c generated by valac 0.34.4, the Vala compiler
 * generated from copy-task.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SEAFILE_TYPE_COPY_TASK (seafile_copy_task_get_type ())
#define SEAFILE_COPY_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_COPY_TASK, SeafileCopyTask))
#define SEAFILE_COPY_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_COPY_TASK, SeafileCopyTaskClass))
#define SEAFILE_IS_COPY_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_COPY_TASK))
#define SEAFILE_IS_COPY_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_COPY_TASK))
#define SEAFILE_COPY_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_COPY_TASK, SeafileCopyTaskClass))

typedef struct _SeafileCopyTask SeafileCopyTask;
typedef struct _SeafileCopyTaskClass SeafileCopyTaskClass;
typedef struct _SeafileCopyTaskPrivate SeafileCopyTaskPrivate;

#define SEAFILE_TYPE_COPY_RESULT (seafile_copy_result_get_type ())
#define SEAFILE_COPY_RESULT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_COPY_RESULT, SeafileCopyResult))
#define SEAFILE_COPY_RESULT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_COPY_RESULT, SeafileCopyResultClass))
#define SEAFILE_IS_COPY_RESULT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_COPY_RESULT))
#define SEAFILE_IS_COPY_RESULT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_COPY_RESULT))
#define SEAFILE_COPY_RESULT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_COPY_RESULT, SeafileCopyResultClass))

typedef struct _SeafileCopyResult SeafileCopyResult;
typedef struct _SeafileCopyResultClass SeafileCopyResultClass;
typedef struct _SeafileCopyResultPrivate SeafileCopyResultPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SeafileCopyTask {
	GObject parent_instance;
	SeafileCopyTaskPrivate * priv;
};

struct _SeafileCopyTaskClass {
	GObjectClass parent_class;
};

struct _SeafileCopyTaskPrivate {
	gint64 _done;
	gint64 _total;
	gboolean _canceled;
	gboolean _failed;
	gboolean _successful;
};

struct _SeafileCopyResult {
	GObject parent_instance;
	SeafileCopyResultPrivate * priv;
};

struct _SeafileCopyResultClass {
	GObjectClass parent_class;
};

struct _SeafileCopyResultPrivate {
	gboolean _background;
	gchar* _task_id;
};


static gpointer seafile_copy_task_parent_class = NULL;
static gpointer seafile_copy_result_parent_class = NULL;

GType seafile_copy_task_get_type (void) G_GNUC_CONST;
#define SEAFILE_COPY_TASK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_COPY_TASK, SeafileCopyTaskPrivate))
enum  {
	SEAFILE_COPY_TASK_DUMMY_PROPERTY,
	SEAFILE_COPY_TASK_DONE,
	SEAFILE_COPY_TASK_TOTAL,
	SEAFILE_COPY_TASK_CANCELED,
	SEAFILE_COPY_TASK_FAILED,
	SEAFILE_COPY_TASK_SUCCESSFUL
};
SeafileCopyTask* seafile_copy_task_new (void);
SeafileCopyTask* seafile_copy_task_construct (GType object_type);
gint64 seafile_copy_task_get_done (SeafileCopyTask* self);
void seafile_copy_task_set_done (SeafileCopyTask* self, gint64 value);
gint64 seafile_copy_task_get_total (SeafileCopyTask* self);
void seafile_copy_task_set_total (SeafileCopyTask* self, gint64 value);
gboolean seafile_copy_task_get_canceled (SeafileCopyTask* self);
void seafile_copy_task_set_canceled (SeafileCopyTask* self, gboolean value);
gboolean seafile_copy_task_get_failed (SeafileCopyTask* self);
void seafile_copy_task_set_failed (SeafileCopyTask* self, gboolean value);
gboolean seafile_copy_task_get_successful (SeafileCopyTask* self);
void seafile_copy_task_set_successful (SeafileCopyTask* self, gboolean value);
static void seafile_copy_task_finalize (GObject* obj);
static void _vala_seafile_copy_task_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_copy_task_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType seafile_copy_result_get_type (void) G_GNUC_CONST;
#define SEAFILE_COPY_RESULT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_COPY_RESULT, SeafileCopyResultPrivate))
enum  {
	SEAFILE_COPY_RESULT_DUMMY_PROPERTY,
	SEAFILE_COPY_RESULT_BACKGROUND,
	SEAFILE_COPY_RESULT_TASK_ID
};
SeafileCopyResult* seafile_copy_result_new (void);
SeafileCopyResult* seafile_copy_result_construct (GType object_type);
gboolean seafile_copy_result_get_background (SeafileCopyResult* self);
void seafile_copy_result_set_background (SeafileCopyResult* self, gboolean value);
const gchar* seafile_copy_result_get_task_id (SeafileCopyResult* self);
void seafile_copy_result_set_task_id (SeafileCopyResult* self, const gchar* value);
static void seafile_copy_result_finalize (GObject* obj);
static void _vala_seafile_copy_result_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_copy_result_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SeafileCopyTask* seafile_copy_task_construct (GType object_type) {
	SeafileCopyTask * self = NULL;
	self = (SeafileCopyTask*) g_object_new (object_type, NULL);
	return self;
}


SeafileCopyTask* seafile_copy_task_new (void) {
	return seafile_copy_task_construct (SEAFILE_TYPE_COPY_TASK);
}


gint64 seafile_copy_task_get_done (SeafileCopyTask* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_done;
	result = _tmp0_;
	return result;
}


void seafile_copy_task_set_done (SeafileCopyTask* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_done = _tmp0_;
	g_object_notify ((GObject *) self, "done");
}


gint64 seafile_copy_task_get_total (SeafileCopyTask* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_total;
	result = _tmp0_;
	return result;
}


void seafile_copy_task_set_total (SeafileCopyTask* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_total = _tmp0_;
	g_object_notify ((GObject *) self, "total");
}


gboolean seafile_copy_task_get_canceled (SeafileCopyTask* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_canceled;
	result = _tmp0_;
	return result;
}


void seafile_copy_task_set_canceled (SeafileCopyTask* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_canceled = _tmp0_;
	g_object_notify ((GObject *) self, "canceled");
}


gboolean seafile_copy_task_get_failed (SeafileCopyTask* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_failed;
	result = _tmp0_;
	return result;
}


void seafile_copy_task_set_failed (SeafileCopyTask* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_failed = _tmp0_;
	g_object_notify ((GObject *) self, "failed");
}


gboolean seafile_copy_task_get_successful (SeafileCopyTask* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_successful;
	result = _tmp0_;
	return result;
}


void seafile_copy_task_set_successful (SeafileCopyTask* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_successful = _tmp0_;
	g_object_notify ((GObject *) self, "successful");
}


static void seafile_copy_task_class_init (SeafileCopyTaskClass * klass) {
	seafile_copy_task_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileCopyTaskPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_copy_task_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_copy_task_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_copy_task_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COPY_TASK_DONE, g_param_spec_int64 ("done", "done", "done", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COPY_TASK_TOTAL, g_param_spec_int64 ("total", "total", "total", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COPY_TASK_CANCELED, g_param_spec_boolean ("canceled", "canceled", "canceled", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COPY_TASK_FAILED, g_param_spec_boolean ("failed", "failed", "failed", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COPY_TASK_SUCCESSFUL, g_param_spec_boolean ("successful", "successful", "successful", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_copy_task_instance_init (SeafileCopyTask * self) {
	self->priv = SEAFILE_COPY_TASK_GET_PRIVATE (self);
}


static void seafile_copy_task_finalize (GObject* obj) {
	SeafileCopyTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_COPY_TASK, SeafileCopyTask);
	G_OBJECT_CLASS (seafile_copy_task_parent_class)->finalize (obj);
}


GType seafile_copy_task_get_type (void) {
	static volatile gsize seafile_copy_task_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_copy_task_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileCopyTaskClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_copy_task_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileCopyTask), 0, (GInstanceInitFunc) seafile_copy_task_instance_init, NULL };
		GType seafile_copy_task_type_id;
		seafile_copy_task_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileCopyTask", &g_define_type_info, 0);
		g_once_init_leave (&seafile_copy_task_type_id__volatile, seafile_copy_task_type_id);
	}
	return seafile_copy_task_type_id__volatile;
}


static void _vala_seafile_copy_task_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileCopyTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_COPY_TASK, SeafileCopyTask);
	switch (property_id) {
		case SEAFILE_COPY_TASK_DONE:
		g_value_set_int64 (value, seafile_copy_task_get_done (self));
		break;
		case SEAFILE_COPY_TASK_TOTAL:
		g_value_set_int64 (value, seafile_copy_task_get_total (self));
		break;
		case SEAFILE_COPY_TASK_CANCELED:
		g_value_set_boolean (value, seafile_copy_task_get_canceled (self));
		break;
		case SEAFILE_COPY_TASK_FAILED:
		g_value_set_boolean (value, seafile_copy_task_get_failed (self));
		break;
		case SEAFILE_COPY_TASK_SUCCESSFUL:
		g_value_set_boolean (value, seafile_copy_task_get_successful (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_copy_task_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileCopyTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_COPY_TASK, SeafileCopyTask);
	switch (property_id) {
		case SEAFILE_COPY_TASK_DONE:
		seafile_copy_task_set_done (self, g_value_get_int64 (value));
		break;
		case SEAFILE_COPY_TASK_TOTAL:
		seafile_copy_task_set_total (self, g_value_get_int64 (value));
		break;
		case SEAFILE_COPY_TASK_CANCELED:
		seafile_copy_task_set_canceled (self, g_value_get_boolean (value));
		break;
		case SEAFILE_COPY_TASK_FAILED:
		seafile_copy_task_set_failed (self, g_value_get_boolean (value));
		break;
		case SEAFILE_COPY_TASK_SUCCESSFUL:
		seafile_copy_task_set_successful (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


SeafileCopyResult* seafile_copy_result_construct (GType object_type) {
	SeafileCopyResult * self = NULL;
	self = (SeafileCopyResult*) g_object_new (object_type, NULL);
	return self;
}


SeafileCopyResult* seafile_copy_result_new (void) {
	return seafile_copy_result_construct (SEAFILE_TYPE_COPY_RESULT);
}


gboolean seafile_copy_result_get_background (SeafileCopyResult* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_background;
	result = _tmp0_;
	return result;
}


void seafile_copy_result_set_background (SeafileCopyResult* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_background = _tmp0_;
	g_object_notify ((GObject *) self, "background");
}


const gchar* seafile_copy_result_get_task_id (SeafileCopyResult* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_task_id;
	result = _tmp0_;
	return result;
}


void seafile_copy_result_set_task_id (SeafileCopyResult* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_task_id);
	self->priv->_task_id = _tmp1_;
	g_object_notify ((GObject *) self, "task-id");
}


static void seafile_copy_result_class_init (SeafileCopyResultClass * klass) {
	seafile_copy_result_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileCopyResultPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_copy_result_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_copy_result_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_copy_result_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COPY_RESULT_BACKGROUND, g_param_spec_boolean ("background", "background", "background", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_COPY_RESULT_TASK_ID, g_param_spec_string ("task-id", "task-id", "task-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_copy_result_instance_init (SeafileCopyResult * self) {
	self->priv = SEAFILE_COPY_RESULT_GET_PRIVATE (self);
}


static void seafile_copy_result_finalize (GObject* obj) {
	SeafileCopyResult * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_COPY_RESULT, SeafileCopyResult);
	_g_free0 (self->priv->_task_id);
	G_OBJECT_CLASS (seafile_copy_result_parent_class)->finalize (obj);
}


GType seafile_copy_result_get_type (void) {
	static volatile gsize seafile_copy_result_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_copy_result_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileCopyResultClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_copy_result_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileCopyResult), 0, (GInstanceInitFunc) seafile_copy_result_instance_init, NULL };
		GType seafile_copy_result_type_id;
		seafile_copy_result_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileCopyResult", &g_define_type_info, 0);
		g_once_init_leave (&seafile_copy_result_type_id__volatile, seafile_copy_result_type_id);
	}
	return seafile_copy_result_type_id__volatile;
}


static void _vala_seafile_copy_result_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileCopyResult * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_COPY_RESULT, SeafileCopyResult);
	switch (property_id) {
		case SEAFILE_COPY_RESULT_BACKGROUND:
		g_value_set_boolean (value, seafile_copy_result_get_background (self));
		break;
		case SEAFILE_COPY_RESULT_TASK_ID:
		g_value_set_string (value, seafile_copy_result_get_task_id (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_copy_result_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileCopyResult * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_COPY_RESULT, SeafileCopyResult);
	switch (property_id) {
		case SEAFILE_COPY_RESULT_BACKGROUND:
		seafile_copy_result_set_background (self, g_value_get_boolean (value));
		break;
		case SEAFILE_COPY_RESULT_TASK_ID:
		seafile_copy_result_set_task_id (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



