/* crypt.c generated by valac 0.34.4, the Vala compiler
 * generated from crypt.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SEAFILE_TYPE_CRYPT_KEY (seafile_crypt_key_get_type ())
#define SEAFILE_CRYPT_KEY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_CRYPT_KEY, SeafileCryptKey))
#define SEAFILE_CRYPT_KEY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_CRYPT_KEY, SeafileCryptKeyClass))
#define SEAFILE_IS_CRYPT_KEY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_CRYPT_KEY))
#define SEAFILE_IS_CRYPT_KEY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_CRYPT_KEY))
#define SEAFILE_CRYPT_KEY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_CRYPT_KEY, SeafileCryptKeyClass))

typedef struct _SeafileCryptKey SeafileCryptKey;
typedef struct _SeafileCryptKeyClass SeafileCryptKeyClass;
typedef struct _SeafileCryptKeyPrivate SeafileCryptKeyPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SeafileCryptKey {
	GObject parent_instance;
	SeafileCryptKeyPrivate * priv;
};

struct _SeafileCryptKeyClass {
	GObjectClass parent_class;
};

struct _SeafileCryptKeyPrivate {
	gchar* _key;
	gchar* _iv;
};


static gpointer seafile_crypt_key_parent_class = NULL;

GType seafile_crypt_key_get_type (void) G_GNUC_CONST;
#define SEAFILE_CRYPT_KEY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_CRYPT_KEY, SeafileCryptKeyPrivate))
enum  {
	SEAFILE_CRYPT_KEY_DUMMY_PROPERTY,
	SEAFILE_CRYPT_KEY_KEY,
	SEAFILE_CRYPT_KEY_IV
};
SeafileCryptKey* seafile_crypt_key_new (void);
SeafileCryptKey* seafile_crypt_key_construct (GType object_type);
const gchar* seafile_crypt_key_get_key (SeafileCryptKey* self);
void seafile_crypt_key_set_key (SeafileCryptKey* self, const gchar* value);
const gchar* seafile_crypt_key_get_iv (SeafileCryptKey* self);
void seafile_crypt_key_set_iv (SeafileCryptKey* self, const gchar* value);
static void seafile_crypt_key_finalize (GObject* obj);
static void _vala_seafile_crypt_key_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_crypt_key_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SeafileCryptKey* seafile_crypt_key_construct (GType object_type) {
	SeafileCryptKey * self = NULL;
	self = (SeafileCryptKey*) g_object_new (object_type, NULL);
	return self;
}


SeafileCryptKey* seafile_crypt_key_new (void) {
	return seafile_crypt_key_construct (SEAFILE_TYPE_CRYPT_KEY);
}


const gchar* seafile_crypt_key_get_key (SeafileCryptKey* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_key;
	result = _tmp0_;
	return result;
}


void seafile_crypt_key_set_key (SeafileCryptKey* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_key);
	self->priv->_key = _tmp1_;
	g_object_notify ((GObject *) self, "key");
}


const gchar* seafile_crypt_key_get_iv (SeafileCryptKey* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_iv;
	result = _tmp0_;
	return result;
}


void seafile_crypt_key_set_iv (SeafileCryptKey* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_iv);
	self->priv->_iv = _tmp1_;
	g_object_notify ((GObject *) self, "iv");
}


static void seafile_crypt_key_class_init (SeafileCryptKeyClass * klass) {
	seafile_crypt_key_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileCryptKeyPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_crypt_key_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_crypt_key_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_crypt_key_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CRYPT_KEY_KEY, g_param_spec_string ("key", "key", "key", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CRYPT_KEY_IV, g_param_spec_string ("iv", "iv", "iv", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_crypt_key_instance_init (SeafileCryptKey * self) {
	self->priv = SEAFILE_CRYPT_KEY_GET_PRIVATE (self);
}


static void seafile_crypt_key_finalize (GObject* obj) {
	SeafileCryptKey * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_CRYPT_KEY, SeafileCryptKey);
	_g_free0 (self->priv->_key);
	_g_free0 (self->priv->_iv);
	G_OBJECT_CLASS (seafile_crypt_key_parent_class)->finalize (obj);
}


GType seafile_crypt_key_get_type (void) {
	static volatile gsize seafile_crypt_key_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_crypt_key_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileCryptKeyClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_crypt_key_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileCryptKey), 0, (GInstanceInitFunc) seafile_crypt_key_instance_init, NULL };
		GType seafile_crypt_key_type_id;
		seafile_crypt_key_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileCryptKey", &g_define_type_info, 0);
		g_once_init_leave (&seafile_crypt_key_type_id__volatile, seafile_crypt_key_type_id);
	}
	return seafile_crypt_key_type_id__volatile;
}


static void _vala_seafile_crypt_key_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileCryptKey * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_CRYPT_KEY, SeafileCryptKey);
	switch (property_id) {
		case SEAFILE_CRYPT_KEY_KEY:
		g_value_set_string (value, seafile_crypt_key_get_key (self));
		break;
		case SEAFILE_CRYPT_KEY_IV:
		g_value_set_string (value, seafile_crypt_key_get_iv (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_crypt_key_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileCryptKey * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_CRYPT_KEY, SeafileCryptKey);
	switch (property_id) {
		case SEAFILE_CRYPT_KEY_KEY:
		seafile_crypt_key_set_key (self, g_value_get_string (value));
		break;
		case SEAFILE_CRYPT_KEY_IV:
		seafile_crypt_key_set_iv (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



