/* dirent.c generated by valac 0.34.4, the Vala compiler
 * generated from dirent.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SEAFILE_TYPE_DIRENT (seafile_dirent_get_type ())
#define SEAFILE_DIRENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_DIRENT, SeafileDirent))
#define SEAFILE_DIRENT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_DIRENT, SeafileDirentClass))
#define SEAFILE_IS_DIRENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_DIRENT))
#define SEAFILE_IS_DIRENT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_DIRENT))
#define SEAFILE_DIRENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_DIRENT, SeafileDirentClass))

typedef struct _SeafileDirent SeafileDirent;
typedef struct _SeafileDirentClass SeafileDirentClass;
typedef struct _SeafileDirentPrivate SeafileDirentPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO (seafile_file_last_modified_info_get_type ())
#define SEAFILE_FILE_LAST_MODIFIED_INFO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO, SeafileFileLastModifiedInfo))
#define SEAFILE_FILE_LAST_MODIFIED_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO, SeafileFileLastModifiedInfoClass))
#define SEAFILE_IS_FILE_LAST_MODIFIED_INFO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO))
#define SEAFILE_IS_FILE_LAST_MODIFIED_INFO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO))
#define SEAFILE_FILE_LAST_MODIFIED_INFO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO, SeafileFileLastModifiedInfoClass))

typedef struct _SeafileFileLastModifiedInfo SeafileFileLastModifiedInfo;
typedef struct _SeafileFileLastModifiedInfoClass SeafileFileLastModifiedInfoClass;
typedef struct _SeafileFileLastModifiedInfoPrivate SeafileFileLastModifiedInfoPrivate;

struct _SeafileDirent {
	GObject parent_instance;
	SeafileDirentPrivate * priv;
};

struct _SeafileDirentClass {
	GObjectClass parent_class;
};

struct _SeafileDirentPrivate {
	gchar* _obj_id;
	gchar* _obj_name;
	gint _mode;
	gint _version;
	gint64 _mtime;
	gint64 _size;
	gchar* _modifier;
	gchar* _permission;
	gboolean _is_locked;
	gchar* _lock_owner;
	gint64 _lock_time;
	gboolean _is_shared;
};

struct _SeafileFileLastModifiedInfo {
	GObject parent_instance;
	SeafileFileLastModifiedInfoPrivate * priv;
};

struct _SeafileFileLastModifiedInfoClass {
	GObjectClass parent_class;
};

struct _SeafileFileLastModifiedInfoPrivate {
	gchar* _file_name;
	gint64 _last_modified;
};


static gpointer seafile_dirent_parent_class = NULL;
static gpointer seafile_file_last_modified_info_parent_class = NULL;

GType seafile_dirent_get_type (void) G_GNUC_CONST;
#define SEAFILE_DIRENT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_DIRENT, SeafileDirentPrivate))
enum  {
	SEAFILE_DIRENT_DUMMY_PROPERTY,
	SEAFILE_DIRENT_OBJ_ID,
	SEAFILE_DIRENT_OBJ_NAME,
	SEAFILE_DIRENT_MODE,
	SEAFILE_DIRENT_VERSION,
	SEAFILE_DIRENT_MTIME,
	SEAFILE_DIRENT_SIZE,
	SEAFILE_DIRENT_MODIFIER,
	SEAFILE_DIRENT_PERMISSION,
	SEAFILE_DIRENT_IS_LOCKED,
	SEAFILE_DIRENT_LOCK_OWNER,
	SEAFILE_DIRENT_LOCK_TIME,
	SEAFILE_DIRENT_IS_SHARED
};
SeafileDirent* seafile_dirent_new (void);
SeafileDirent* seafile_dirent_construct (GType object_type);
const gchar* seafile_dirent_get_obj_id (SeafileDirent* self);
void seafile_dirent_set_obj_id (SeafileDirent* self, const gchar* value);
const gchar* seafile_dirent_get_obj_name (SeafileDirent* self);
void seafile_dirent_set_obj_name (SeafileDirent* self, const gchar* value);
gint seafile_dirent_get_mode (SeafileDirent* self);
void seafile_dirent_set_mode (SeafileDirent* self, gint value);
gint seafile_dirent_get_version (SeafileDirent* self);
void seafile_dirent_set_version (SeafileDirent* self, gint value);
gint64 seafile_dirent_get_mtime (SeafileDirent* self);
void seafile_dirent_set_mtime (SeafileDirent* self, gint64 value);
gint64 seafile_dirent_get_size (SeafileDirent* self);
void seafile_dirent_set_size (SeafileDirent* self, gint64 value);
const gchar* seafile_dirent_get_modifier (SeafileDirent* self);
void seafile_dirent_set_modifier (SeafileDirent* self, const gchar* value);
const gchar* seafile_dirent_get_permission (SeafileDirent* self);
void seafile_dirent_set_permission (SeafileDirent* self, const gchar* value);
gboolean seafile_dirent_get_is_locked (SeafileDirent* self);
void seafile_dirent_set_is_locked (SeafileDirent* self, gboolean value);
const gchar* seafile_dirent_get_lock_owner (SeafileDirent* self);
void seafile_dirent_set_lock_owner (SeafileDirent* self, const gchar* value);
gint64 seafile_dirent_get_lock_time (SeafileDirent* self);
void seafile_dirent_set_lock_time (SeafileDirent* self, gint64 value);
gboolean seafile_dirent_get_is_shared (SeafileDirent* self);
void seafile_dirent_set_is_shared (SeafileDirent* self, gboolean value);
static void seafile_dirent_finalize (GObject* obj);
static void _vala_seafile_dirent_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_dirent_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType seafile_file_last_modified_info_get_type (void) G_GNUC_CONST;
#define SEAFILE_FILE_LAST_MODIFIED_INFO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO, SeafileFileLastModifiedInfoPrivate))
enum  {
	SEAFILE_FILE_LAST_MODIFIED_INFO_DUMMY_PROPERTY,
	SEAFILE_FILE_LAST_MODIFIED_INFO_FILE_NAME,
	SEAFILE_FILE_LAST_MODIFIED_INFO_LAST_MODIFIED
};
SeafileFileLastModifiedInfo* seafile_file_last_modified_info_new (void);
SeafileFileLastModifiedInfo* seafile_file_last_modified_info_construct (GType object_type);
const gchar* seafile_file_last_modified_info_get_file_name (SeafileFileLastModifiedInfo* self);
void seafile_file_last_modified_info_set_file_name (SeafileFileLastModifiedInfo* self, const gchar* value);
gint64 seafile_file_last_modified_info_get_last_modified (SeafileFileLastModifiedInfo* self);
void seafile_file_last_modified_info_set_last_modified (SeafileFileLastModifiedInfo* self, gint64 value);
static void seafile_file_last_modified_info_finalize (GObject* obj);
static void _vala_seafile_file_last_modified_info_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_file_last_modified_info_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SeafileDirent* seafile_dirent_construct (GType object_type) {
	SeafileDirent * self = NULL;
	self = (SeafileDirent*) g_object_new (object_type, NULL);
	return self;
}


SeafileDirent* seafile_dirent_new (void) {
	return seafile_dirent_construct (SEAFILE_TYPE_DIRENT);
}


const gchar* seafile_dirent_get_obj_id (SeafileDirent* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_obj_id;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_obj_id (SeafileDirent* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_obj_id);
	self->priv->_obj_id = _tmp1_;
	g_object_notify ((GObject *) self, "obj-id");
}


const gchar* seafile_dirent_get_obj_name (SeafileDirent* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_obj_name;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_obj_name (SeafileDirent* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_obj_name);
	self->priv->_obj_name = _tmp1_;
	g_object_notify ((GObject *) self, "obj-name");
}


gint seafile_dirent_get_mode (SeafileDirent* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_mode;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_mode (SeafileDirent* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_mode = _tmp0_;
	g_object_notify ((GObject *) self, "mode");
}


gint seafile_dirent_get_version (SeafileDirent* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_version;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_version (SeafileDirent* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_version = _tmp0_;
	g_object_notify ((GObject *) self, "version");
}


gint64 seafile_dirent_get_mtime (SeafileDirent* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_mtime;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_mtime (SeafileDirent* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_mtime = _tmp0_;
	g_object_notify ((GObject *) self, "mtime");
}


gint64 seafile_dirent_get_size (SeafileDirent* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_size;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_size (SeafileDirent* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_size = _tmp0_;
	g_object_notify ((GObject *) self, "size");
}


const gchar* seafile_dirent_get_modifier (SeafileDirent* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_modifier;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_modifier (SeafileDirent* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_modifier);
	self->priv->_modifier = _tmp1_;
	g_object_notify ((GObject *) self, "modifier");
}


const gchar* seafile_dirent_get_permission (SeafileDirent* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_permission;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_permission (SeafileDirent* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_permission);
	self->priv->_permission = _tmp1_;
	g_object_notify ((GObject *) self, "permission");
}


gboolean seafile_dirent_get_is_locked (SeafileDirent* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_is_locked;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_is_locked (SeafileDirent* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_is_locked = _tmp0_;
	g_object_notify ((GObject *) self, "is-locked");
}


const gchar* seafile_dirent_get_lock_owner (SeafileDirent* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_lock_owner;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_lock_owner (SeafileDirent* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_lock_owner);
	self->priv->_lock_owner = _tmp1_;
	g_object_notify ((GObject *) self, "lock-owner");
}


gint64 seafile_dirent_get_lock_time (SeafileDirent* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_lock_time;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_lock_time (SeafileDirent* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_lock_time = _tmp0_;
	g_object_notify ((GObject *) self, "lock-time");
}


gboolean seafile_dirent_get_is_shared (SeafileDirent* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_is_shared;
	result = _tmp0_;
	return result;
}


void seafile_dirent_set_is_shared (SeafileDirent* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_is_shared = _tmp0_;
	g_object_notify ((GObject *) self, "is-shared");
}


static void seafile_dirent_class_init (SeafileDirentClass * klass) {
	seafile_dirent_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileDirentPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_dirent_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_dirent_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_dirent_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_OBJ_ID, g_param_spec_string ("obj-id", "obj-id", "obj-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_OBJ_NAME, g_param_spec_string ("obj-name", "obj-name", "obj-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_MODE, g_param_spec_int ("mode", "mode", "mode", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_VERSION, g_param_spec_int ("version", "version", "version", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_MTIME, g_param_spec_int64 ("mtime", "mtime", "mtime", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_SIZE, g_param_spec_int64 ("size", "size", "size", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_MODIFIER, g_param_spec_string ("modifier", "modifier", "modifier", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_PERMISSION, g_param_spec_string ("permission", "permission", "permission", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_IS_LOCKED, g_param_spec_boolean ("is-locked", "is-locked", "is-locked", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_LOCK_OWNER, g_param_spec_string ("lock-owner", "lock-owner", "lock-owner", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_LOCK_TIME, g_param_spec_int64 ("lock-time", "lock-time", "lock-time", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_DIRENT_IS_SHARED, g_param_spec_boolean ("is-shared", "is-shared", "is-shared", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_dirent_instance_init (SeafileDirent * self) {
	self->priv = SEAFILE_DIRENT_GET_PRIVATE (self);
}


static void seafile_dirent_finalize (GObject* obj) {
	SeafileDirent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_DIRENT, SeafileDirent);
	_g_free0 (self->priv->_obj_id);
	_g_free0 (self->priv->_obj_name);
	_g_free0 (self->priv->_modifier);
	_g_free0 (self->priv->_permission);
	_g_free0 (self->priv->_lock_owner);
	G_OBJECT_CLASS (seafile_dirent_parent_class)->finalize (obj);
}


GType seafile_dirent_get_type (void) {
	static volatile gsize seafile_dirent_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_dirent_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileDirentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_dirent_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileDirent), 0, (GInstanceInitFunc) seafile_dirent_instance_init, NULL };
		GType seafile_dirent_type_id;
		seafile_dirent_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileDirent", &g_define_type_info, 0);
		g_once_init_leave (&seafile_dirent_type_id__volatile, seafile_dirent_type_id);
	}
	return seafile_dirent_type_id__volatile;
}


static void _vala_seafile_dirent_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileDirent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_DIRENT, SeafileDirent);
	switch (property_id) {
		case SEAFILE_DIRENT_OBJ_ID:
		g_value_set_string (value, seafile_dirent_get_obj_id (self));
		break;
		case SEAFILE_DIRENT_OBJ_NAME:
		g_value_set_string (value, seafile_dirent_get_obj_name (self));
		break;
		case SEAFILE_DIRENT_MODE:
		g_value_set_int (value, seafile_dirent_get_mode (self));
		break;
		case SEAFILE_DIRENT_VERSION:
		g_value_set_int (value, seafile_dirent_get_version (self));
		break;
		case SEAFILE_DIRENT_MTIME:
		g_value_set_int64 (value, seafile_dirent_get_mtime (self));
		break;
		case SEAFILE_DIRENT_SIZE:
		g_value_set_int64 (value, seafile_dirent_get_size (self));
		break;
		case SEAFILE_DIRENT_MODIFIER:
		g_value_set_string (value, seafile_dirent_get_modifier (self));
		break;
		case SEAFILE_DIRENT_PERMISSION:
		g_value_set_string (value, seafile_dirent_get_permission (self));
		break;
		case SEAFILE_DIRENT_IS_LOCKED:
		g_value_set_boolean (value, seafile_dirent_get_is_locked (self));
		break;
		case SEAFILE_DIRENT_LOCK_OWNER:
		g_value_set_string (value, seafile_dirent_get_lock_owner (self));
		break;
		case SEAFILE_DIRENT_LOCK_TIME:
		g_value_set_int64 (value, seafile_dirent_get_lock_time (self));
		break;
		case SEAFILE_DIRENT_IS_SHARED:
		g_value_set_boolean (value, seafile_dirent_get_is_shared (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_dirent_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileDirent * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_DIRENT, SeafileDirent);
	switch (property_id) {
		case SEAFILE_DIRENT_OBJ_ID:
		seafile_dirent_set_obj_id (self, g_value_get_string (value));
		break;
		case SEAFILE_DIRENT_OBJ_NAME:
		seafile_dirent_set_obj_name (self, g_value_get_string (value));
		break;
		case SEAFILE_DIRENT_MODE:
		seafile_dirent_set_mode (self, g_value_get_int (value));
		break;
		case SEAFILE_DIRENT_VERSION:
		seafile_dirent_set_version (self, g_value_get_int (value));
		break;
		case SEAFILE_DIRENT_MTIME:
		seafile_dirent_set_mtime (self, g_value_get_int64 (value));
		break;
		case SEAFILE_DIRENT_SIZE:
		seafile_dirent_set_size (self, g_value_get_int64 (value));
		break;
		case SEAFILE_DIRENT_MODIFIER:
		seafile_dirent_set_modifier (self, g_value_get_string (value));
		break;
		case SEAFILE_DIRENT_PERMISSION:
		seafile_dirent_set_permission (self, g_value_get_string (value));
		break;
		case SEAFILE_DIRENT_IS_LOCKED:
		seafile_dirent_set_is_locked (self, g_value_get_boolean (value));
		break;
		case SEAFILE_DIRENT_LOCK_OWNER:
		seafile_dirent_set_lock_owner (self, g_value_get_string (value));
		break;
		case SEAFILE_DIRENT_LOCK_TIME:
		seafile_dirent_set_lock_time (self, g_value_get_int64 (value));
		break;
		case SEAFILE_DIRENT_IS_SHARED:
		seafile_dirent_set_is_shared (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


SeafileFileLastModifiedInfo* seafile_file_last_modified_info_construct (GType object_type) {
	SeafileFileLastModifiedInfo * self = NULL;
	self = (SeafileFileLastModifiedInfo*) g_object_new (object_type, NULL);
	return self;
}


SeafileFileLastModifiedInfo* seafile_file_last_modified_info_new (void) {
	return seafile_file_last_modified_info_construct (SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO);
}


const gchar* seafile_file_last_modified_info_get_file_name (SeafileFileLastModifiedInfo* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_file_name;
	result = _tmp0_;
	return result;
}


void seafile_file_last_modified_info_set_file_name (SeafileFileLastModifiedInfo* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_file_name);
	self->priv->_file_name = _tmp1_;
	g_object_notify ((GObject *) self, "file-name");
}


gint64 seafile_file_last_modified_info_get_last_modified (SeafileFileLastModifiedInfo* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_last_modified;
	result = _tmp0_;
	return result;
}


void seafile_file_last_modified_info_set_last_modified (SeafileFileLastModifiedInfo* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_last_modified = _tmp0_;
	g_object_notify ((GObject *) self, "last-modified");
}


static void seafile_file_last_modified_info_class_init (SeafileFileLastModifiedInfoClass * klass) {
	seafile_file_last_modified_info_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileFileLastModifiedInfoPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_file_last_modified_info_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_file_last_modified_info_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_file_last_modified_info_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_FILE_LAST_MODIFIED_INFO_FILE_NAME, g_param_spec_string ("file-name", "file-name", "file-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_FILE_LAST_MODIFIED_INFO_LAST_MODIFIED, g_param_spec_int64 ("last-modified", "last-modified", "last-modified", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_file_last_modified_info_instance_init (SeafileFileLastModifiedInfo * self) {
	self->priv = SEAFILE_FILE_LAST_MODIFIED_INFO_GET_PRIVATE (self);
}


static void seafile_file_last_modified_info_finalize (GObject* obj) {
	SeafileFileLastModifiedInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO, SeafileFileLastModifiedInfo);
	_g_free0 (self->priv->_file_name);
	G_OBJECT_CLASS (seafile_file_last_modified_info_parent_class)->finalize (obj);
}


GType seafile_file_last_modified_info_get_type (void) {
	static volatile gsize seafile_file_last_modified_info_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_file_last_modified_info_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileFileLastModifiedInfoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_file_last_modified_info_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileFileLastModifiedInfo), 0, (GInstanceInitFunc) seafile_file_last_modified_info_instance_init, NULL };
		GType seafile_file_last_modified_info_type_id;
		seafile_file_last_modified_info_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileFileLastModifiedInfo", &g_define_type_info, 0);
		g_once_init_leave (&seafile_file_last_modified_info_type_id__volatile, seafile_file_last_modified_info_type_id);
	}
	return seafile_file_last_modified_info_type_id__volatile;
}


static void _vala_seafile_file_last_modified_info_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileFileLastModifiedInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO, SeafileFileLastModifiedInfo);
	switch (property_id) {
		case SEAFILE_FILE_LAST_MODIFIED_INFO_FILE_NAME:
		g_value_set_string (value, seafile_file_last_modified_info_get_file_name (self));
		break;
		case SEAFILE_FILE_LAST_MODIFIED_INFO_LAST_MODIFIED:
		g_value_set_int64 (value, seafile_file_last_modified_info_get_last_modified (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_file_last_modified_info_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileFileLastModifiedInfo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_FILE_LAST_MODIFIED_INFO, SeafileFileLastModifiedInfo);
	switch (property_id) {
		case SEAFILE_FILE_LAST_MODIFIED_INFO_FILE_NAME:
		seafile_file_last_modified_info_set_file_name (self, g_value_get_string (value));
		break;
		case SEAFILE_FILE_LAST_MODIFIED_INFO_LAST_MODIFIED:
		seafile_file_last_modified_info_set_last_modified (self, g_value_get_int64 (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



