/* task.c generated by valac 0.34.4, the Vala compiler
 * generated from task.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <string.h>


#define SEAFILE_TYPE_TASK (seafile_task_get_type ())
#define SEAFILE_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_TASK, SeafileTask))
#define SEAFILE_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_TASK, SeafileTaskClass))
#define SEAFILE_IS_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_TASK))
#define SEAFILE_IS_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_TASK))
#define SEAFILE_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_TASK, SeafileTaskClass))

typedef struct _SeafileTask SeafileTask;
typedef struct _SeafileTaskClass SeafileTaskClass;
typedef struct _SeafileTaskPrivate SeafileTaskPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

#define SEAFILE_TYPE_CLONE_TASK (seafile_clone_task_get_type ())
#define SEAFILE_CLONE_TASK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_CLONE_TASK, SeafileCloneTask))
#define SEAFILE_CLONE_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_CLONE_TASK, SeafileCloneTaskClass))
#define SEAFILE_IS_CLONE_TASK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_CLONE_TASK))
#define SEAFILE_IS_CLONE_TASK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_CLONE_TASK))
#define SEAFILE_CLONE_TASK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_CLONE_TASK, SeafileCloneTaskClass))

typedef struct _SeafileCloneTask SeafileCloneTask;
typedef struct _SeafileCloneTaskClass SeafileCloneTaskClass;
typedef struct _SeafileCloneTaskPrivate SeafileCloneTaskPrivate;

struct _SeafileTask {
	GObject parent_instance;
	SeafileTaskPrivate * priv;
	gchar _tx_id[37];
	gint64 _rsize;
	gint64 _dsize;
};

struct _SeafileTaskClass {
	GObjectClass parent_class;
};

struct _SeafileTaskPrivate {
	gchar* _ttype;
	gchar* _repo_id;
	gchar* _dest_id;
	gchar* _from_branch;
	gchar* _to_branch;
	gchar* _state;
	gchar* _rt_state;
	gchar* _error_str;
	gint _block_total;
	gint _block_done;
	gint _fs_objects_total;
	gint _fs_objects_done;
	gint _rate;
};

struct _SeafileCloneTask {
	GObject parent_instance;
	SeafileCloneTaskPrivate * priv;
};

struct _SeafileCloneTaskClass {
	GObjectClass parent_class;
};

struct _SeafileCloneTaskPrivate {
	gchar* _state;
	gchar* _error_str;
	gchar* _repo_id;
	gchar* _peer_id;
	gchar* _repo_name;
	gchar* _worktree;
	gchar* _tx_id;
};


static gpointer seafile_task_parent_class = NULL;
static gpointer seafile_clone_task_parent_class = NULL;

GType seafile_task_get_type (void) G_GNUC_CONST;
#define SEAFILE_TASK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_TASK, SeafileTaskPrivate))
enum  {
	SEAFILE_TASK_DUMMY_PROPERTY,
	SEAFILE_TASK_TX_ID,
	SEAFILE_TASK_TTYPE,
	SEAFILE_TASK_REPO_ID,
	SEAFILE_TASK_DEST_ID,
	SEAFILE_TASK_FROM_BRANCH,
	SEAFILE_TASK_TO_BRANCH,
	SEAFILE_TASK_STATE,
	SEAFILE_TASK_RT_STATE,
	SEAFILE_TASK_ERROR_STR,
	SEAFILE_TASK_BLOCK_TOTAL,
	SEAFILE_TASK_BLOCK_DONE,
	SEAFILE_TASK_FS_OBJECTS_TOTAL,
	SEAFILE_TASK_FS_OBJECTS_DONE,
	SEAFILE_TASK_RATE,
	SEAFILE_TASK_RSIZE,
	SEAFILE_TASK_DSIZE
};
SeafileTask* seafile_task_new (void);
SeafileTask* seafile_task_construct (GType object_type);
const gchar* seafile_task_get_tx_id (SeafileTask* self);
void seafile_task_set_tx_id (SeafileTask* self, const gchar* value);
const gchar* seafile_task_get_ttype (SeafileTask* self);
void seafile_task_set_ttype (SeafileTask* self, const gchar* value);
const gchar* seafile_task_get_repo_id (SeafileTask* self);
void seafile_task_set_repo_id (SeafileTask* self, const gchar* value);
const gchar* seafile_task_get_dest_id (SeafileTask* self);
void seafile_task_set_dest_id (SeafileTask* self, const gchar* value);
const gchar* seafile_task_get_from_branch (SeafileTask* self);
void seafile_task_set_from_branch (SeafileTask* self, const gchar* value);
const gchar* seafile_task_get_to_branch (SeafileTask* self);
void seafile_task_set_to_branch (SeafileTask* self, const gchar* value);
const gchar* seafile_task_get_state (SeafileTask* self);
void seafile_task_set_state (SeafileTask* self, const gchar* value);
const gchar* seafile_task_get_rt_state (SeafileTask* self);
void seafile_task_set_rt_state (SeafileTask* self, const gchar* value);
const gchar* seafile_task_get_error_str (SeafileTask* self);
void seafile_task_set_error_str (SeafileTask* self, const gchar* value);
gint seafile_task_get_block_total (SeafileTask* self);
void seafile_task_set_block_total (SeafileTask* self, gint value);
gint seafile_task_get_block_done (SeafileTask* self);
void seafile_task_set_block_done (SeafileTask* self, gint value);
gint seafile_task_get_fs_objects_total (SeafileTask* self);
void seafile_task_set_fs_objects_total (SeafileTask* self, gint value);
gint seafile_task_get_fs_objects_done (SeafileTask* self);
void seafile_task_set_fs_objects_done (SeafileTask* self, gint value);
gint seafile_task_get_rate (SeafileTask* self);
void seafile_task_set_rate (SeafileTask* self, gint value);
gint64 seafile_task_get_rsize (SeafileTask* self);
void seafile_task_set_rsize (SeafileTask* self, gint64 value);
gint64 seafile_task_get_dsize (SeafileTask* self);
void seafile_task_set_dsize (SeafileTask* self, gint64 value);
static void seafile_task_finalize (GObject* obj);
static void _vala_seafile_task_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_task_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType seafile_clone_task_get_type (void) G_GNUC_CONST;
#define SEAFILE_CLONE_TASK_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_CLONE_TASK, SeafileCloneTaskPrivate))
enum  {
	SEAFILE_CLONE_TASK_DUMMY_PROPERTY,
	SEAFILE_CLONE_TASK_STATE,
	SEAFILE_CLONE_TASK_ERROR_STR,
	SEAFILE_CLONE_TASK_REPO_ID,
	SEAFILE_CLONE_TASK_PEER_ID,
	SEAFILE_CLONE_TASK_REPO_NAME,
	SEAFILE_CLONE_TASK_WORKTREE,
	SEAFILE_CLONE_TASK_TX_ID
};
SeafileCloneTask* seafile_clone_task_new (void);
SeafileCloneTask* seafile_clone_task_construct (GType object_type);
const gchar* seafile_clone_task_get_state (SeafileCloneTask* self);
void seafile_clone_task_set_state (SeafileCloneTask* self, const gchar* value);
const gchar* seafile_clone_task_get_error_str (SeafileCloneTask* self);
void seafile_clone_task_set_error_str (SeafileCloneTask* self, const gchar* value);
const gchar* seafile_clone_task_get_repo_id (SeafileCloneTask* self);
void seafile_clone_task_set_repo_id (SeafileCloneTask* self, const gchar* value);
const gchar* seafile_clone_task_get_peer_id (SeafileCloneTask* self);
void seafile_clone_task_set_peer_id (SeafileCloneTask* self, const gchar* value);
const gchar* seafile_clone_task_get_repo_name (SeafileCloneTask* self);
void seafile_clone_task_set_repo_name (SeafileCloneTask* self, const gchar* value);
const gchar* seafile_clone_task_get_worktree (SeafileCloneTask* self);
void seafile_clone_task_set_worktree (SeafileCloneTask* self, const gchar* value);
const gchar* seafile_clone_task_get_tx_id (SeafileCloneTask* self);
void seafile_clone_task_set_tx_id (SeafileCloneTask* self, const gchar* value);
static void seafile_clone_task_finalize (GObject* obj);
static void _vala_seafile_clone_task_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_clone_task_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SeafileTask* seafile_task_construct (GType object_type) {
	SeafileTask * self = NULL;
	self = (SeafileTask*) g_object_new (object_type, NULL);
	return self;
}


SeafileTask* seafile_task_new (void) {
	return seafile_task_construct (SEAFILE_TYPE_TASK);
}


const gchar* seafile_task_get_tx_id (SeafileTask* self) {
	const gchar* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = (const gchar*) self->_tx_id;
	return result;
}


void seafile_task_set_tx_id (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar _tmp1_ = '\0';
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	memcpy (self->_tx_id, _tmp0_, (gsize) 36);
	self->_tx_id[36] = '\0';
	_tmp1_ = self->_tx_id[36];
	g_object_notify ((GObject *) self, "tx-id");
}


const gchar* seafile_task_get_ttype (SeafileTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_ttype;
	result = _tmp0_;
	return result;
}


void seafile_task_set_ttype (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_ttype);
	self->priv->_ttype = _tmp1_;
	g_object_notify ((GObject *) self, "ttype");
}


const gchar* seafile_task_get_repo_id (SeafileTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_repo_id;
	result = _tmp0_;
	return result;
}


void seafile_task_set_repo_id (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_repo_id);
	self->priv->_repo_id = _tmp1_;
	g_object_notify ((GObject *) self, "repo-id");
}


const gchar* seafile_task_get_dest_id (SeafileTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_dest_id;
	result = _tmp0_;
	return result;
}


void seafile_task_set_dest_id (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_dest_id);
	self->priv->_dest_id = _tmp1_;
	g_object_notify ((GObject *) self, "dest-id");
}


const gchar* seafile_task_get_from_branch (SeafileTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_from_branch;
	result = _tmp0_;
	return result;
}


void seafile_task_set_from_branch (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_from_branch);
	self->priv->_from_branch = _tmp1_;
	g_object_notify ((GObject *) self, "from-branch");
}


const gchar* seafile_task_get_to_branch (SeafileTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_to_branch;
	result = _tmp0_;
	return result;
}


void seafile_task_set_to_branch (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_to_branch);
	self->priv->_to_branch = _tmp1_;
	g_object_notify ((GObject *) self, "to-branch");
}


const gchar* seafile_task_get_state (SeafileTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_state;
	result = _tmp0_;
	return result;
}


void seafile_task_set_state (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_state);
	self->priv->_state = _tmp1_;
	g_object_notify ((GObject *) self, "state");
}


const gchar* seafile_task_get_rt_state (SeafileTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_rt_state;
	result = _tmp0_;
	return result;
}


void seafile_task_set_rt_state (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_rt_state);
	self->priv->_rt_state = _tmp1_;
	g_object_notify ((GObject *) self, "rt-state");
}


const gchar* seafile_task_get_error_str (SeafileTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_error_str;
	result = _tmp0_;
	return result;
}


void seafile_task_set_error_str (SeafileTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_error_str);
	self->priv->_error_str = _tmp1_;
	g_object_notify ((GObject *) self, "error-str");
}


gint seafile_task_get_block_total (SeafileTask* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_block_total;
	result = _tmp0_;
	return result;
}


void seafile_task_set_block_total (SeafileTask* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_block_total = _tmp0_;
	g_object_notify ((GObject *) self, "block-total");
}


gint seafile_task_get_block_done (SeafileTask* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_block_done;
	result = _tmp0_;
	return result;
}


void seafile_task_set_block_done (SeafileTask* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_block_done = _tmp0_;
	g_object_notify ((GObject *) self, "block-done");
}


gint seafile_task_get_fs_objects_total (SeafileTask* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_fs_objects_total;
	result = _tmp0_;
	return result;
}


void seafile_task_set_fs_objects_total (SeafileTask* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_fs_objects_total = _tmp0_;
	g_object_notify ((GObject *) self, "fs-objects-total");
}


gint seafile_task_get_fs_objects_done (SeafileTask* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_fs_objects_done;
	result = _tmp0_;
	return result;
}


void seafile_task_set_fs_objects_done (SeafileTask* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_fs_objects_done = _tmp0_;
	g_object_notify ((GObject *) self, "fs-objects-done");
}


gint seafile_task_get_rate (SeafileTask* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_rate;
	result = _tmp0_;
	return result;
}


void seafile_task_set_rate (SeafileTask* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_rate = _tmp0_;
	g_object_notify ((GObject *) self, "rate");
}


gint64 seafile_task_get_rsize (SeafileTask* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->_rsize;
	result = _tmp0_;
	return result;
}


void seafile_task_set_rsize (SeafileTask* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->_rsize = _tmp0_;
	g_object_notify ((GObject *) self, "rsize");
}


gint64 seafile_task_get_dsize (SeafileTask* self) {
	gint64 result;
	gint64 _tmp0_ = 0LL;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->_dsize;
	result = _tmp0_;
	return result;
}


void seafile_task_set_dsize (SeafileTask* self, gint64 value) {
	gint64 _tmp0_ = 0LL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->_dsize = _tmp0_;
	g_object_notify ((GObject *) self, "dsize");
}


static void seafile_task_class_init (SeafileTaskClass * klass) {
	seafile_task_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileTaskPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_task_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_task_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_task_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_TX_ID, g_param_spec_string ("tx-id", "tx-id", "tx-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_TTYPE, g_param_spec_string ("ttype", "ttype", "ttype", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_REPO_ID, g_param_spec_string ("repo-id", "repo-id", "repo-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_DEST_ID, g_param_spec_string ("dest-id", "dest-id", "dest-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_FROM_BRANCH, g_param_spec_string ("from-branch", "from-branch", "from-branch", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_TO_BRANCH, g_param_spec_string ("to-branch", "to-branch", "to-branch", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_STATE, g_param_spec_string ("state", "state", "state", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_RT_STATE, g_param_spec_string ("rt-state", "rt-state", "rt-state", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_ERROR_STR, g_param_spec_string ("error-str", "error-str", "error-str", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_BLOCK_TOTAL, g_param_spec_int ("block-total", "block-total", "block-total", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_BLOCK_DONE, g_param_spec_int ("block-done", "block-done", "block-done", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_FS_OBJECTS_TOTAL, g_param_spec_int ("fs-objects-total", "fs-objects-total", "fs-objects-total", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_FS_OBJECTS_DONE, g_param_spec_int ("fs-objects-done", "fs-objects-done", "fs-objects-done", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_RATE, g_param_spec_int ("rate", "rate", "rate", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_RSIZE, g_param_spec_int64 ("rsize", "rsize", "rsize", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_TASK_DSIZE, g_param_spec_int64 ("dsize", "dsize", "dsize", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_task_instance_init (SeafileTask * self) {
	self->priv = SEAFILE_TASK_GET_PRIVATE (self);
}


static void seafile_task_finalize (GObject* obj) {
	SeafileTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_TASK, SeafileTask);
	_g_free0 (self->priv->_ttype);
	_g_free0 (self->priv->_repo_id);
	_g_free0 (self->priv->_dest_id);
	_g_free0 (self->priv->_from_branch);
	_g_free0 (self->priv->_to_branch);
	_g_free0 (self->priv->_state);
	_g_free0 (self->priv->_rt_state);
	_g_free0 (self->priv->_error_str);
	G_OBJECT_CLASS (seafile_task_parent_class)->finalize (obj);
}


GType seafile_task_get_type (void) {
	static volatile gsize seafile_task_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_task_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileTaskClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_task_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileTask), 0, (GInstanceInitFunc) seafile_task_instance_init, NULL };
		GType seafile_task_type_id;
		seafile_task_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileTask", &g_define_type_info, 0);
		g_once_init_leave (&seafile_task_type_id__volatile, seafile_task_type_id);
	}
	return seafile_task_type_id__volatile;
}


static void _vala_seafile_task_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_TASK, SeafileTask);
	switch (property_id) {
		case SEAFILE_TASK_TX_ID:
		g_value_set_string (value, seafile_task_get_tx_id (self));
		break;
		case SEAFILE_TASK_TTYPE:
		g_value_set_string (value, seafile_task_get_ttype (self));
		break;
		case SEAFILE_TASK_REPO_ID:
		g_value_set_string (value, seafile_task_get_repo_id (self));
		break;
		case SEAFILE_TASK_DEST_ID:
		g_value_set_string (value, seafile_task_get_dest_id (self));
		break;
		case SEAFILE_TASK_FROM_BRANCH:
		g_value_set_string (value, seafile_task_get_from_branch (self));
		break;
		case SEAFILE_TASK_TO_BRANCH:
		g_value_set_string (value, seafile_task_get_to_branch (self));
		break;
		case SEAFILE_TASK_STATE:
		g_value_set_string (value, seafile_task_get_state (self));
		break;
		case SEAFILE_TASK_RT_STATE:
		g_value_set_string (value, seafile_task_get_rt_state (self));
		break;
		case SEAFILE_TASK_ERROR_STR:
		g_value_set_string (value, seafile_task_get_error_str (self));
		break;
		case SEAFILE_TASK_BLOCK_TOTAL:
		g_value_set_int (value, seafile_task_get_block_total (self));
		break;
		case SEAFILE_TASK_BLOCK_DONE:
		g_value_set_int (value, seafile_task_get_block_done (self));
		break;
		case SEAFILE_TASK_FS_OBJECTS_TOTAL:
		g_value_set_int (value, seafile_task_get_fs_objects_total (self));
		break;
		case SEAFILE_TASK_FS_OBJECTS_DONE:
		g_value_set_int (value, seafile_task_get_fs_objects_done (self));
		break;
		case SEAFILE_TASK_RATE:
		g_value_set_int (value, seafile_task_get_rate (self));
		break;
		case SEAFILE_TASK_RSIZE:
		g_value_set_int64 (value, seafile_task_get_rsize (self));
		break;
		case SEAFILE_TASK_DSIZE:
		g_value_set_int64 (value, seafile_task_get_dsize (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_task_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_TASK, SeafileTask);
	switch (property_id) {
		case SEAFILE_TASK_TX_ID:
		seafile_task_set_tx_id (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_TTYPE:
		seafile_task_set_ttype (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_REPO_ID:
		seafile_task_set_repo_id (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_DEST_ID:
		seafile_task_set_dest_id (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_FROM_BRANCH:
		seafile_task_set_from_branch (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_TO_BRANCH:
		seafile_task_set_to_branch (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_STATE:
		seafile_task_set_state (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_RT_STATE:
		seafile_task_set_rt_state (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_ERROR_STR:
		seafile_task_set_error_str (self, g_value_get_string (value));
		break;
		case SEAFILE_TASK_BLOCK_TOTAL:
		seafile_task_set_block_total (self, g_value_get_int (value));
		break;
		case SEAFILE_TASK_BLOCK_DONE:
		seafile_task_set_block_done (self, g_value_get_int (value));
		break;
		case SEAFILE_TASK_FS_OBJECTS_TOTAL:
		seafile_task_set_fs_objects_total (self, g_value_get_int (value));
		break;
		case SEAFILE_TASK_FS_OBJECTS_DONE:
		seafile_task_set_fs_objects_done (self, g_value_get_int (value));
		break;
		case SEAFILE_TASK_RATE:
		seafile_task_set_rate (self, g_value_get_int (value));
		break;
		case SEAFILE_TASK_RSIZE:
		seafile_task_set_rsize (self, g_value_get_int64 (value));
		break;
		case SEAFILE_TASK_DSIZE:
		seafile_task_set_dsize (self, g_value_get_int64 (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


SeafileCloneTask* seafile_clone_task_construct (GType object_type) {
	SeafileCloneTask * self = NULL;
	self = (SeafileCloneTask*) g_object_new (object_type, NULL);
	return self;
}


SeafileCloneTask* seafile_clone_task_new (void) {
	return seafile_clone_task_construct (SEAFILE_TYPE_CLONE_TASK);
}


const gchar* seafile_clone_task_get_state (SeafileCloneTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_state;
	result = _tmp0_;
	return result;
}


void seafile_clone_task_set_state (SeafileCloneTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_state);
	self->priv->_state = _tmp1_;
	g_object_notify ((GObject *) self, "state");
}


const gchar* seafile_clone_task_get_error_str (SeafileCloneTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_error_str;
	result = _tmp0_;
	return result;
}


void seafile_clone_task_set_error_str (SeafileCloneTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_error_str);
	self->priv->_error_str = _tmp1_;
	g_object_notify ((GObject *) self, "error-str");
}


const gchar* seafile_clone_task_get_repo_id (SeafileCloneTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_repo_id;
	result = _tmp0_;
	return result;
}


void seafile_clone_task_set_repo_id (SeafileCloneTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_repo_id);
	self->priv->_repo_id = _tmp1_;
	g_object_notify ((GObject *) self, "repo-id");
}


const gchar* seafile_clone_task_get_peer_id (SeafileCloneTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_peer_id;
	result = _tmp0_;
	return result;
}


void seafile_clone_task_set_peer_id (SeafileCloneTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_peer_id);
	self->priv->_peer_id = _tmp1_;
	g_object_notify ((GObject *) self, "peer-id");
}


const gchar* seafile_clone_task_get_repo_name (SeafileCloneTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_repo_name;
	result = _tmp0_;
	return result;
}


void seafile_clone_task_set_repo_name (SeafileCloneTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_repo_name);
	self->priv->_repo_name = _tmp1_;
	g_object_notify ((GObject *) self, "repo-name");
}


const gchar* seafile_clone_task_get_worktree (SeafileCloneTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_worktree;
	result = _tmp0_;
	return result;
}


void seafile_clone_task_set_worktree (SeafileCloneTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_worktree);
	self->priv->_worktree = _tmp1_;
	g_object_notify ((GObject *) self, "worktree");
}


const gchar* seafile_clone_task_get_tx_id (SeafileCloneTask* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_tx_id;
	result = _tmp0_;
	return result;
}


void seafile_clone_task_set_tx_id (SeafileCloneTask* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_tx_id);
	self->priv->_tx_id = _tmp1_;
	g_object_notify ((GObject *) self, "tx-id");
}


static void seafile_clone_task_class_init (SeafileCloneTaskClass * klass) {
	seafile_clone_task_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileCloneTaskPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_clone_task_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_clone_task_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_clone_task_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CLONE_TASK_STATE, g_param_spec_string ("state", "state", "state", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CLONE_TASK_ERROR_STR, g_param_spec_string ("error-str", "error-str", "error-str", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CLONE_TASK_REPO_ID, g_param_spec_string ("repo-id", "repo-id", "repo-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CLONE_TASK_PEER_ID, g_param_spec_string ("peer-id", "peer-id", "peer-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CLONE_TASK_REPO_NAME, g_param_spec_string ("repo-name", "repo-name", "repo-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CLONE_TASK_WORKTREE, g_param_spec_string ("worktree", "worktree", "worktree", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_CLONE_TASK_TX_ID, g_param_spec_string ("tx-id", "tx-id", "tx-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_clone_task_instance_init (SeafileCloneTask * self) {
	self->priv = SEAFILE_CLONE_TASK_GET_PRIVATE (self);
}


static void seafile_clone_task_finalize (GObject* obj) {
	SeafileCloneTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_CLONE_TASK, SeafileCloneTask);
	_g_free0 (self->priv->_state);
	_g_free0 (self->priv->_error_str);
	_g_free0 (self->priv->_repo_id);
	_g_free0 (self->priv->_peer_id);
	_g_free0 (self->priv->_repo_name);
	_g_free0 (self->priv->_worktree);
	_g_free0 (self->priv->_tx_id);
	G_OBJECT_CLASS (seafile_clone_task_parent_class)->finalize (obj);
}


GType seafile_clone_task_get_type (void) {
	static volatile gsize seafile_clone_task_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_clone_task_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileCloneTaskClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_clone_task_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileCloneTask), 0, (GInstanceInitFunc) seafile_clone_task_instance_init, NULL };
		GType seafile_clone_task_type_id;
		seafile_clone_task_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileCloneTask", &g_define_type_info, 0);
		g_once_init_leave (&seafile_clone_task_type_id__volatile, seafile_clone_task_type_id);
	}
	return seafile_clone_task_type_id__volatile;
}


static void _vala_seafile_clone_task_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileCloneTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_CLONE_TASK, SeafileCloneTask);
	switch (property_id) {
		case SEAFILE_CLONE_TASK_STATE:
		g_value_set_string (value, seafile_clone_task_get_state (self));
		break;
		case SEAFILE_CLONE_TASK_ERROR_STR:
		g_value_set_string (value, seafile_clone_task_get_error_str (self));
		break;
		case SEAFILE_CLONE_TASK_REPO_ID:
		g_value_set_string (value, seafile_clone_task_get_repo_id (self));
		break;
		case SEAFILE_CLONE_TASK_PEER_ID:
		g_value_set_string (value, seafile_clone_task_get_peer_id (self));
		break;
		case SEAFILE_CLONE_TASK_REPO_NAME:
		g_value_set_string (value, seafile_clone_task_get_repo_name (self));
		break;
		case SEAFILE_CLONE_TASK_WORKTREE:
		g_value_set_string (value, seafile_clone_task_get_worktree (self));
		break;
		case SEAFILE_CLONE_TASK_TX_ID:
		g_value_set_string (value, seafile_clone_task_get_tx_id (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_clone_task_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileCloneTask * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_CLONE_TASK, SeafileCloneTask);
	switch (property_id) {
		case SEAFILE_CLONE_TASK_STATE:
		seafile_clone_task_set_state (self, g_value_get_string (value));
		break;
		case SEAFILE_CLONE_TASK_ERROR_STR:
		seafile_clone_task_set_error_str (self, g_value_get_string (value));
		break;
		case SEAFILE_CLONE_TASK_REPO_ID:
		seafile_clone_task_set_repo_id (self, g_value_get_string (value));
		break;
		case SEAFILE_CLONE_TASK_PEER_ID:
		seafile_clone_task_set_peer_id (self, g_value_get_string (value));
		break;
		case SEAFILE_CLONE_TASK_REPO_NAME:
		seafile_clone_task_set_repo_name (self, g_value_get_string (value));
		break;
		case SEAFILE_CLONE_TASK_WORKTREE:
		seafile_clone_task_set_worktree (self, g_value_get_string (value));
		break;
		case SEAFILE_CLONE_TASK_TX_ID:
		seafile_clone_task_set_tx_id (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



