/* webaccess.c generated by valac 0.34.4, the Vala compiler
 * generated from webaccess.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define SEAFILE_TYPE_WEB_ACCESS (seafile_web_access_get_type ())
#define SEAFILE_WEB_ACCESS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SEAFILE_TYPE_WEB_ACCESS, SeafileWebAccess))
#define SEAFILE_WEB_ACCESS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SEAFILE_TYPE_WEB_ACCESS, SeafileWebAccessClass))
#define SEAFILE_IS_WEB_ACCESS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SEAFILE_TYPE_WEB_ACCESS))
#define SEAFILE_IS_WEB_ACCESS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SEAFILE_TYPE_WEB_ACCESS))
#define SEAFILE_WEB_ACCESS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SEAFILE_TYPE_WEB_ACCESS, SeafileWebAccessClass))

typedef struct _SeafileWebAccess SeafileWebAccess;
typedef struct _SeafileWebAccessClass SeafileWebAccessClass;
typedef struct _SeafileWebAccessPrivate SeafileWebAccessPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SeafileWebAccess {
	GObject parent_instance;
	SeafileWebAccessPrivate * priv;
};

struct _SeafileWebAccessClass {
	GObjectClass parent_class;
};

struct _SeafileWebAccessPrivate {
	gchar* _repo_id;
	gchar* _obj_id;
	gchar* _op;
	gchar* _username;
};


static gpointer seafile_web_access_parent_class = NULL;

GType seafile_web_access_get_type (void) G_GNUC_CONST;
#define SEAFILE_WEB_ACCESS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SEAFILE_TYPE_WEB_ACCESS, SeafileWebAccessPrivate))
enum  {
	SEAFILE_WEB_ACCESS_DUMMY_PROPERTY,
	SEAFILE_WEB_ACCESS_REPO_ID,
	SEAFILE_WEB_ACCESS_OBJ_ID,
	SEAFILE_WEB_ACCESS_OP,
	SEAFILE_WEB_ACCESS_USERNAME
};
SeafileWebAccess* seafile_web_access_new (void);
SeafileWebAccess* seafile_web_access_construct (GType object_type);
const gchar* seafile_web_access_get_repo_id (SeafileWebAccess* self);
void seafile_web_access_set_repo_id (SeafileWebAccess* self, const gchar* value);
const gchar* seafile_web_access_get_obj_id (SeafileWebAccess* self);
void seafile_web_access_set_obj_id (SeafileWebAccess* self, const gchar* value);
const gchar* seafile_web_access_get_op (SeafileWebAccess* self);
void seafile_web_access_set_op (SeafileWebAccess* self, const gchar* value);
const gchar* seafile_web_access_get_username (SeafileWebAccess* self);
void seafile_web_access_set_username (SeafileWebAccess* self, const gchar* value);
static void seafile_web_access_finalize (GObject* obj);
static void _vala_seafile_web_access_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_seafile_web_access_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


SeafileWebAccess* seafile_web_access_construct (GType object_type) {
	SeafileWebAccess * self = NULL;
	self = (SeafileWebAccess*) g_object_new (object_type, NULL);
	return self;
}


SeafileWebAccess* seafile_web_access_new (void) {
	return seafile_web_access_construct (SEAFILE_TYPE_WEB_ACCESS);
}


const gchar* seafile_web_access_get_repo_id (SeafileWebAccess* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_repo_id;
	result = _tmp0_;
	return result;
}


void seafile_web_access_set_repo_id (SeafileWebAccess* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_repo_id);
	self->priv->_repo_id = _tmp1_;
	g_object_notify ((GObject *) self, "repo-id");
}


const gchar* seafile_web_access_get_obj_id (SeafileWebAccess* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_obj_id;
	result = _tmp0_;
	return result;
}


void seafile_web_access_set_obj_id (SeafileWebAccess* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_obj_id);
	self->priv->_obj_id = _tmp1_;
	g_object_notify ((GObject *) self, "obj-id");
}


const gchar* seafile_web_access_get_op (SeafileWebAccess* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_op;
	result = _tmp0_;
	return result;
}


void seafile_web_access_set_op (SeafileWebAccess* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_op);
	self->priv->_op = _tmp1_;
	g_object_notify ((GObject *) self, "op");
}


const gchar* seafile_web_access_get_username (SeafileWebAccess* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_username;
	result = _tmp0_;
	return result;
}


void seafile_web_access_set_username (SeafileWebAccess* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_username);
	self->priv->_username = _tmp1_;
	g_object_notify ((GObject *) self, "username");
}


static void seafile_web_access_class_init (SeafileWebAccessClass * klass) {
	seafile_web_access_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SeafileWebAccessPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_seafile_web_access_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_seafile_web_access_set_property;
	G_OBJECT_CLASS (klass)->finalize = seafile_web_access_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_WEB_ACCESS_REPO_ID, g_param_spec_string ("repo-id", "repo-id", "repo-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_WEB_ACCESS_OBJ_ID, g_param_spec_string ("obj-id", "obj-id", "obj-id", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_WEB_ACCESS_OP, g_param_spec_string ("op", "op", "op", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), SEAFILE_WEB_ACCESS_USERNAME, g_param_spec_string ("username", "username", "username", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void seafile_web_access_instance_init (SeafileWebAccess * self) {
	self->priv = SEAFILE_WEB_ACCESS_GET_PRIVATE (self);
}


static void seafile_web_access_finalize (GObject* obj) {
	SeafileWebAccess * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SEAFILE_TYPE_WEB_ACCESS, SeafileWebAccess);
	_g_free0 (self->priv->_repo_id);
	_g_free0 (self->priv->_obj_id);
	_g_free0 (self->priv->_op);
	_g_free0 (self->priv->_username);
	G_OBJECT_CLASS (seafile_web_access_parent_class)->finalize (obj);
}


GType seafile_web_access_get_type (void) {
	static volatile gsize seafile_web_access_type_id__volatile = 0;
	if (g_once_init_enter (&seafile_web_access_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SeafileWebAccessClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) seafile_web_access_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SeafileWebAccess), 0, (GInstanceInitFunc) seafile_web_access_instance_init, NULL };
		GType seafile_web_access_type_id;
		seafile_web_access_type_id = g_type_register_static (G_TYPE_OBJECT, "SeafileWebAccess", &g_define_type_info, 0);
		g_once_init_leave (&seafile_web_access_type_id__volatile, seafile_web_access_type_id);
	}
	return seafile_web_access_type_id__volatile;
}


static void _vala_seafile_web_access_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	SeafileWebAccess * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_WEB_ACCESS, SeafileWebAccess);
	switch (property_id) {
		case SEAFILE_WEB_ACCESS_REPO_ID:
		g_value_set_string (value, seafile_web_access_get_repo_id (self));
		break;
		case SEAFILE_WEB_ACCESS_OBJ_ID:
		g_value_set_string (value, seafile_web_access_get_obj_id (self));
		break;
		case SEAFILE_WEB_ACCESS_OP:
		g_value_set_string (value, seafile_web_access_get_op (self));
		break;
		case SEAFILE_WEB_ACCESS_USERNAME:
		g_value_set_string (value, seafile_web_access_get_username (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_seafile_web_access_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	SeafileWebAccess * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SEAFILE_TYPE_WEB_ACCESS, SeafileWebAccess);
	switch (property_id) {
		case SEAFILE_WEB_ACCESS_REPO_ID:
		seafile_web_access_set_repo_id (self, g_value_get_string (value));
		break;
		case SEAFILE_WEB_ACCESS_OBJ_ID:
		seafile_web_access_set_obj_id (self, g_value_get_string (value));
		break;
		case SEAFILE_WEB_ACCESS_OP:
		seafile_web_access_set_op (self, g_value_get_string (value));
		break;
		case SEAFILE_WEB_ACCESS_USERNAME:
		seafile_web_access_set_username (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



